import type { DB } from "./types";

export const EDITIONS = [2010, 2014, 2018, 2022, 2026];

export const FLAGS: Record<string, string> = {
  Spain: "🇪🇸",
  Netherlands: "🇳🇱",
  Germany: "🇩🇪",
  Brazil: "🇧🇷",
  Argentina: "🇦🇷",
  Uruguay: "🇺🇾",
  Portugal: "🇵🇹",
  France: "🇫🇷",
  Belgium: "🇧🇪",
  Colombia: "🇨🇴",
  Croatia: "🇭🇷",
  England: "🇬🇧",
  Morocco: "🇲🇦",
  Mexico: "🇲🇽",
  "South Africa": "🇿🇦",
  Nigeria: "🇳🇬",
  "South Korea": "🇰🇷",
  Greece: "🇬🇷",
  USA: "🇺🇸",
  Algeria: "🇩🇿",
  Slovenia: "🇸🇮",
  Australia: "🇦🇺",
  Serbia: "🇷🇸",
  Ghana: "🇬🇭",
  Denmark: "🇩🇰",
  Japan: "🇯🇵",
  Cameroon: "🇨🇲",
  Italy: "🇮🇹",
  Paraguay: "🇵🇾",
  "New Zealand": "🇳🇿",
  Slovakia: "🇸🇰",
  "Ivory Coast": "🇨🇮",
  "North Korea": "🇰🇵",
  Switzerland: "🇨🇭",
  Chile: "🇨🇱",
  Honduras: "🇭🇳",
  "Costa Rica": "🇨🇷",
  "Bosnia and Herzegovina": "🇧🇦",
  Iran: "🇮🇷",
  Russia: "🇷🇺",
  "Saudi Arabia": "🇸🇦",
  Egypt: "🇪🇬",
  Peru: "🇵🇪",
  Iceland: "🇮🇸",
  Tunisia: "🇹🇳",
  Panama: "🇵🇦",
  Poland: "🇵🇱",
  Senegal: "🇸🇳",
  Ecuador: "🇪🇨",
  Czechia: "🇨🇿",
};

export const WORLD_CUP_DB: DB = {
  2010: {
    Uruguay: [
      ["Fernando Muslera", "GK", 84],
      ["Diego Lugano", "CB", 87],
      ["Jorge Fucile", "RB", 81],
      ["Martín Cáceres", "CB", 84],
      ["Maxi Pereira", "RB", 82],
      ["Walter Gargano", "CDM", 80],
      ["Diego Pérez", "CDM", 79],
      ["Álvaro Pereira", "LM", 82],
      ["Egidio Arévalo Ríos", "CDM", 81],
      ["Nicolás Lodeiro", "CAM", 80],
      ["Rodrigo Palacio", "ST", 78],
      ["Sebastián Eguren", "CM", 78],
      ["Juan Castillo", "GK", 72],
      ["Mauricio Victorino", "CB", 78],
      ["Andrés Scotti", "CB", 79],
      ["Sebastián Coates", "CB", 76],
      ["Álvaro Fernández", "GK", 71],
      ["Alvaro González", "RM", 77],
      ["Néstor Muslera", "GK", 70],
      ["Diego Forlán", "ST", 91],
      ["Edinson Cavani", "ST", 88],
      ["Luis Suárez", "ST", 89],
      ["Abel Hernández", "ST", 77],
      ["Álvaro Pereira", "LM", 82],
    ],
    Mexico: [
      ["Óscar Pérez", "GK", 78],
      ["Joaquín Beltrán", "CB", 74],
      ["Francisco Rodríguez", "CB", 82],
      ["Rafael Márquez", "CB", 86],
      ["Carlos Salcido", "LB", 83],
      ["Gerardo Torrado", "CDM", 81],
      ["Andrés Guardado", "LM", 83],
      ["Efraín Juárez", "RB", 76],
      ["Giovani dos Santos", "RW", 83],
      ["Cuauhtémoc Blanco", "CAM", 79],
      ["Javier Hernández", "ST", 84],
      ["Alberto Medina", "RM", 74],
      ["Guillermo Ochoa", "GK", 80],
      ["Jonny Magallón", "CB", 77],
      ["Héctor Moreno", "CB", 81],
      ["Paul Aguilar", "RB", 75],
      ["Adolfo Bautista", "RM", 73],
      ["Israel Castro", "CDM", 76],
      ["Pablo Barrera", "RW", 79],
      ["Javier Aguirre", "CM", 70],
      ["Adrián Aldrete", "LB", 72],
      ["Gerardo Galindo", "CM", 71],
      ["Efrain Flores", "CM", 70],
      ["Francisco Palencia", "ST", 72],
    ],
    "South Africa": [
      ["Itumeleng Khune", "GK", 79],
      ["Siboniso Gaxa", "RB", 74],
      ["Bongani Khumalo", "CB", 76],
      ["Aaron Mokoena", "CB", 78],
      ["Lucas Thwala", "LB", 73],
      ["MacBeth Sibaya", "CDM", 74],
      ["Thanduyise Khuboni", "CM", 72],
      ["Siphiwe Tshabalala", "LM", 82],
      ["Steven Pienaar", "CAM", 81],
      ["Teko Modise", "CM", 77],
      ["Katlego Mphela", "ST", 80],
      ["Mandla Masango", "RW", 72],
      ["Moeneeb Josephs", "GK", 76],
      ["Lehlohonolo Majoro", "ST", 71],
      ["Nasief Morris", "CB", 72],
      ["Busa Mkhwanazi", "CB", 70],
      ["Anele Ngcongca", "RB", 73],
      ["Thulani Serero", "CAM", 73],
      ["Bernard Parker", "ST", 76],
      ["Kagisho Dikgacoi", "CDM", 75],
      ["Darren Keet", "GK", 70],
      ["Tsepo Masilela", "LB", 74],
      ["Siboniso Gaxa", "RB", 74],
      ["Mark Mayambela", "LW", 72],
    ],
    France: [
      ["Hugo Lloris", "GK", 83],
      ["Steve Mandanda", "GK", 80],
      ["Cédric Carrasso", "GK", 76],
      ["Patrice Evra", "LB", 82],
      ["William Gallas", "CB", 81],
      ["Abou Diaby", "CM", 78],
      ["Yohan Gourcuff", "CAM", 79],
      ["Alou Diarra", "CDM", 77],
      ["Éric Abidal", "LB", 80],
      ["Bakary Sagna", "RB", 79],
      ["Thierry Henry", "ST", 78],
      ["Franck Ribéry", "LW", 84],
      ["Nicolas Anelka", "ST", 77],
      ["Jérémy Toulalan", "CDM", 78],
      ["Florent Malouda", "LM", 80],
      ["Nicolas Plestan", "CB", 71],
      ["Gaël Clichy", "LB", 75],
      ["Mathieu Valbuena", "RW", 80],
      ["Abou Diaby", "CM", 78],
      ["Sidney Govou", "RW", 74],
      ["André-Pierre Gignac", "ST", 75],
      ["Yoann Gourcuff", "CAM", 79],
      ["Jean-Alain Boumsong", "CB", 72],
      ["William Gallas", "CB", 81],
    ],
    Argentina: [
      ["Sergio Romero", "GK", 84],
      ["Diego Pozo", "GK", 72],
      ["Nicolás Otamendi", "CB", 78],
      ["Martín Demichelis", "CB", 81],
      ["Walter Samuel", "CB", 82],
      ["Gabriel Heinze", "LB", 79],
      ["Jonás Gutiérrez", "RM", 77],
      ["Marcos Angeleri", "RB", 72],
      ["Nicolás Burdisso", "CB", 76],
      ["Javier Zanetti", "RB", 80],
      ["Javier Mascherano", "CDM", 88],
      ["Juan Sebastián Verón", "CM", 78],
      ["Ángel Di María", "LW", 84],
      ["Fernando Gago", "CM", 76],
      ["Maxi Rodríguez", "LM", 78],
      ["Mario Bolatti", "CM", 73],
      ["Juan Sebastián Verón", "CM", 78],
      ["Javier Pastore", "CAM", 77],
      ["Éver Banega", "CM", 76],
      ["Lionel Messi", "CF", 92],
      ["Carlos Tévez", "ST", 87],
      ["Gonzalo Higuaín", "ST", 90],
      ["Diego Milito", "ST", 85],
    ],
    Nigeria: [
      ["Vincent Enyeama", "GK", 84],
      ["Austin Ejide", "GK", 74],
      ["Peter Odemwingie", "RW", 82],
      ["Chidi Odiah", "RB", 74],
      ["Joseph Yobo", "CB", 80],
      ["Taye Taiwo", "LB", 81],
      ["Danny Shittu", "CB", 73],
      ["Rabiu Afolabi", "CB", 72],
      ["Dickson Etuhu", "CDM", 76],
      ["Ayila Yussuf", "CDM", 74],
      ["Kalu Uche", "CM", 75],
      ["Ogenyi Onazi", "CM", 70],
      ["John Mikel Obi", "CM", 83],
      ["Sani Kaita", "CDM", 72],
      ["Elderson Echiejile", "LB", 71],
      ["Victor Anichebe", "ST", 74],
      ["Yakubu Aiyegbeni", "ST", 78],
      ["Chinedu Obasi", "RW", 77],
      ["Kanu", "CF", 75],
      ["Obafemi Martins", "ST", 79],
      ["Daniel Shittu", "CB", 73],
      ["Aiyegbeni Yakubu", "ST", 78],
      ["Victor Nsofor", "LW", 76],
    ],
    "South Korea": [
      ["Jung Sung-ryong", "GK", 80],
      ["Lee Woon-jae", "GK", 73],
      ["Lee Young-pyo", "LB", 82],
      ["Cha Du-ri", "RB", 78],
      ["Kim Jae-sung", "CB", 74],
      ["Cho Sung-hwan", "CB", 75],
      ["Lee Jung-soo", "CB", 79],
      ["Kim Nam-il", "CDM", 77],
      ["Park Ji-sung", "CM", 86],
      ["Ki Sung-yueng", "CM", 80],
      ["Kim Jung-woo", "CM", 76],
      ["Lee Chung-yong", "RW", 83],
      ["Park Chu-young", "ST", 81],
      ["Yeom Ki-hun", "LM", 76],
      ["Moon Tae-jong", "CM", 71],
      ["Lee Dong-gook", "ST", 74],
      ["Hwang Jae-won", "RB", 73],
      ["Kim Dong-jin", "LB", 74],
      ["Lee Ho", "CDM", 72],
      ["Oh Beom-seok", "RB", 71],
      ["Song Chong-gug", "RB", 70],
      ["Kim Bo-kyung", "CAM", 74],
      ["Yeom Ki-hun", "LM", 76],
    ],
    Greece: [
      ["Alexandros Tzorvas", "GK", 79],
      ["Michalis Sifakis", "GK", 74],
      ["Vasilis Torosidis", "RB", 81],
      ["Sokratis Papastathopoulos", "CB", 82],
      ["Loukas Vintra", "CB", 76],
      ["Avraam Papadopoulos", "CB", 78],
      ["Giourkas Seitaridis", "RB", 74],
      ["Vasilis Karagounis", "CM", 80],
      ["Kostas Katsouranis", "CDM", 82],
      ["Giorgos Karagounis", "CAM", 83],
      ["Giorgos Samaras", "LW", 81],
      ["Dimitris Salpingidis", "ST", 82],
      ["Theofanis Gekas", "ST", 84],
      ["Sotiris Ninis", "CAM", 77],
      ["Vangelis Moras", "CB", 75],
      ["Christos Patsatzoglou", "CDM", 74],
      ["Alexandros Tziolis", "CM", 73],
      ["Kostas Chalkias", "GK", 71],
      ["Dimitrios Papadopoulos", "ST", 75],
      ["Giorgos Fotakis", "CM", 74],
      ["Nikos Spiropoulos", "LB", 75],
      ["Jose Holebas", "LB", 73],
      ["Lazaros Christodoulopoulos", "RW", 74],
    ],
    England: [
      ["David James", "GK", 78],
      ["Robert Green", "GK", 72],
      ["Joe Hart", "GK", 74],
      ["Glen Johnson", "RB", 80],
      ["Jamie Carragher", "CB", 73],
      ["John Terry", "CB", 79],
      ["Ledley King", "CB", 76],
      ["Rio Ferdinand", "CB", 70],
      ["Matthew Upson", "CB", 77],
      ["Ashley Cole", "LB", 84],
      ["Stephen Warnock", "LB", 71],
      ["Michael Dawson", "CB", 72],
      ["Steven Gerrard", "CM", 84],
      ["Frank Lampard", "CM", 82],
      ["Gareth Barry", "CDM", 76],
      ["James Milner", "RM", 79],
      ["Aaron Lennon", "RW", 74],
      ["Joe Cole", "LW", 72],
      ["Shaun Wright-Phillips", "RW", 71],
      ["Tom Huddlestone", "CM", 70],
      ["Peter Crouch", "ST", 75],
      ["Wayne Rooney", "ST", 74],
      ["Jermain Defoe", "ST", 76],
    ],
    USA: [
      ["Tim Howard", "GK", 86],
      ["Brad Guzan", "GK", 72],
      ["Marcus Hahnemann", "GK", 71],
      ["Carlos Bocanegra", "LB", 80],
      ["Jay DeMerit", "CB", 78],
      ["Oguchi Onyewu", "CB", 72],
      ["Jonathan Bornstein", "LB", 70],
      ["Steve Cherundolo", "RB", 84],
      ["Jonathan Spector", "RB", 71],
      ["Clarence Goodson", "CB", 73],
      ["Chad Marshall", "CB", 70],
      ["Michael Bradley", "CM", 83],
      ["Clint Dempsey", "RW", 87],
      ["Landon Donovan", "RW", 90],
      ["Ricardo Clark", "CDM", 71],
      ["Maurice Edu", "CDM", 75],
      ["Benny Feilhaber", "CM", 76],
      ["José Francisco Torres", "CM", 72],
      ["Stuart Holden", "RM", 73],
      ["DaMarcus Beasley", "LM", 71],
      ["Jozy Altidore", "ST", 78],
      ["Edson Buddle", "ST", 72],
      ["Herculez Gomez", "ST", 73],
    ],
    Algeria: [
      ["Faouzi Chaouchi", "GK", 74],
      ["Rais M'Bolhi", "GK", 81],
      ["Mohamed Lamine Zemmamouche", "GK", 70],
      ["Madjid Bougherra", "CB", 82],
      ["Rafik Halliche", "CB", 78],
      ["Abdelkader Laïfaoui", "CB", 71],
      ["Carl Medjani", "CB", 74],
      ["Nadir Belhadj", "LB", 80],
      ["Mehdi Lacen", "CDM", 79],
      ["Adlane Guedioura", "CDM", 75],
      ["Hassan Yebda", "CM", 78],
      ["Karim Ziani", "RM", 80],
      ["Mourad Meghni", "CAM", 70],
      ["Yazid Mansouri", "CDM", 73],
      ["Foued Kadir", "RM", 72],
      ["Ryad Boudebouz", "CAM", 70],
      ["Djamel Abdoun", "RW", 71],
      ["Khaled Lemmouchia", "CM", 70],
      ["Abdelmalek Ziaya", "ST", 71],
      ["Rafik Saïfi", "CF", 70],
      ["Nadir Bouazza", "LW", 70],
      ["Rafik Djebbour", "ST", 74],
      ["Kamel Ghilas", "ST", 72],
    ],
    Slovenia: [
      ["Samir Handanović", "GK", 84],
      ["Jasmin Handanović", "GK", 70],
      ["Aleksander Seliga", "GK", 71],
      ["Boštjan Cesar", "CB", 81],
      ["Marko Šuler", "CB", 77],
      ["Miran Pavlin", "CB", 70],
      ["Suad Fileković", "CB", 70],
      ["Mišo Brečko", "RB", 78],
      ["Bojan Jokić", "LB", 79],
      ["Branko Ilič", "RB", 74],
      ["Valter Birsa", "RW", 81],
      ["Andraž Kirm", "LM", 79],
      ["Robert Koren", "CM", 83],
      ["Aleksandar Radosavljevič", "CDM", 76],
      ["Dalibor Stevanovič", "CM", 74],
      ["Rene Krhin", "CDM", 72],
      ["Matej Mavrič", "CB", 70],
      ["Nejc Pečnik", "RM", 71],
      ["Zlatko Dedič", "ST", 78],
      ["Milivoje Novakovič", "ST", 82],
      ["Tim Matavž", "ST", 72],
      ["Zlatan Ljubijankić", "ST", 75],
      ["Etien Velikonja", "ST", 70],
    ],
    Germany: [
      ["Manuel Neuer", "GK", 88],
      ["Hans-Jörg Butt", "GK", 74],
      ["Tim Wiese", "GK", 75],
      ["Philipp Lahm", ["LB", "RB"], 91],
      ["Arne Friedrich", "RB", 78],
      ["Dennis Aogo", "LB", 75],
      ["Holger Badstuber", "CB", 76],
      ["Per Mertesacker", "CB", 81],
      ["Serdar Tasci", "CB", 76],
      ["Jérôme Boateng", ["RB", "CB"], 77],
      ["Marcell Jansen", ["LB", "CM"], 75],
      ["Sami Khedira", "CDM", 84],
      ["Bastian Schweinsteiger", "CM", 87],
      ["Mesut Özil", "CAM", 89],
      ["Thomas Müller", ["CAM", "RW"], 90],
      ["Toni Kroos", "CM", 78],
      ["Piotr Trochowski", "CM", 74],
      ["Marko Marin", "LW", 73],
      ["Lukas Podolski", "LW", 82],
      ["Miroslav Klose", "ST", 85],
      ["Cacau", ["RW", "ST"], 80],
      ["Stefan Kießling", "ST", 72],
      ["Mario Gómez", "ST", 76],
    ],
    Australia: [
      ["Mark Schwarzer", "GK", 82],
      ["Adam Federici", "GK", 70],
      ["Eugene Galekovic", "GK", 70],
      ["Lucas Neill", "RB", 76],
      ["Craig Moore", "CB", 74],
      ["Michael Beauchamp", "CB", 72],
      ["Scott Chipperfield", "CB", 73],
      ["Luke Wilkshire", "RB", 74],
      ["David Carney", "LB", 72],
      ["Mark Milligan", ["CB", "CM"], 72],
      ["Tim Cahill", "CM", 84],
      ["Jason Culina", "CM", 73],
      ["Brett Emerton", ["RM", "RB"], 76],
      ["Vince Grella", "CDM", 73],
      ["Mile Jedinak", "CDM", 72],
      ["Carl Valeri", "CM", 71],
      ["Richard Garcia", "CM", 71],
      ["Dario Vidošić", "CM", 70],
      ["Mark Bresciano", "CAM", 77],
      ["Harry Kewell", "LW", 74],
      ["Brett Holman", ["RW", "ST"], 75],
      ["Joshua Kennedy", "ST", 73],
      ["Nikita Rukavytsya", "ST", 71],
    ],
    Serbia: [
      ["Vladimir Stojković", "GK", 80],
      ["Bojan Isailović", "GK", 70],
      ["Anđelko Đuričić", "GK", 70],
      ["Nemanja Vidić", "CB", 87],
      ["Branislav Ivanović", ["RB", "CB"], 84],
      ["Aleksandar Kolarov", "LB", 81],
      ["Aleksandar Luković", "CB", 75],
      ["Antonio Rukavina", "RB", 73],
      ["Ivan Obradović", "LB", 71],
      ["Neven Subotić", "CB", 76],
      ["Dejan Stanković", "CM", 85],
      ["Miloš Krasić", "RM", 81],
      ["Milan Jovanović", "LW", 80],
      ["Zdravko Kuzmanović", "CDM", 75],
      ["Gojko Kačar", "CM", 73],
      ["Zoran Tošić", "LW", 74],
      ["Nenad Milijaš", "CM", 73],
      ["Miloš Ninković", "CAM", 72],
      ["Radosav Petrović", "CDM", 72],
      ["Nikola Žigić", "ST", 78],
      ["Danko Lazović", "ST", 75],
      ["Marko Pantelić", "ST", 73],
      ["Dragan Mrđa", "ST", 70],
    ],
    Ghana: [
      ["Richard Kingson", "GK", 79],
      ["Daniel Agyei", "GK", 70],
      ["Stephen Ahorlu", "GK", 70],
      ["John Mensah", "CB", 81],
      ["Hans Sarpei", "LB", 76],
      ["John Paintsil", "RB", 77],
      ["Samuel Inkoom", "RB", 73],
      ["Jonathan Mensah", "CB", 72],
      ["Isaac Vorsah", "CB", 72],
      ["Lee Addy", "CB", 70],
      ["Ibrahim Ayew", "LB", 71],
      ["Anthony Annan", "CDM", 78],
      ["Sulley Muntari", "CM", 83],
      ["Stephen Appiah", "CM", 79],
      ["Derek Boateng", "CM", 75],
      ["Kevin-Prince Boateng", ["CM", "CAM"], 82],
      ["Kwadwo Asamoah", ["LM", "CM"], 78],
      ["André Ayew", ["LW", "CAM"], 77],
      ["Quincy Owusu-Abeyie", "LW", 72],
      ["Asamoah Gyan", "ST", 88],
      ["Matthew Amoah", "ST", 73],
      ["Prince Tagoe", "ST", 72],
      ["Dominic Adiyiah", "ST", 72],
    ],
    Netherlands: [
      ["Maarten Stekelenburg", "GK", 86],
      ["Michel Vorm", "GK", 74],
      ["Sander Boschker", "GK", 70],
      ["Gregory van der Wiel", "RB", 83],
      ["Joris Mathijsen", "CB", 82],
      ["John Heitinga", ["CB", "RB"], 83],
      ["Giovanni van Bronckhorst", "LB", 84],
      ["Ron Vlaar", "CB", 78],
      ["Andre Ooijer", "CB", 76],
      ["Khalid Boulahrouz", ["RB", "CB"], 77],
      ["Edson Braafheid", "LB", 73],
      ["Vurnon Anita", "CDM", 74],
      ["Mark van Bommel", "CDM", 85],
      ["Nigel de Jong", "CDM", 86],
      ["Wesley Sneijder", "CAM", 93],
      ["Rafael van der Vaart", ["CAM", "CM"], 86],
      ["Demy de Zeeuw", "CM", 76],
      ["Arjen Robben", "RW", 89],
      ["Dirk Kuyt", ["RW", "ST"], 85],
      ["Eljero Elia", "LW", 79],
      ["Robin van Persie", "ST", 88],
      ["Klaas-Jan Huntelaar", "ST", 82],
      ["Ibrahim Afellay", ["LW", "CAM"], 78],
    ],
    Denmark: [
      ["Thomas Sørensen", "GK", 80],
      ["Stephan Andersen", "GK", 73],
      ["Johan Wiland", "GK", 72],
      ["Simon Poulsen", "LB", 77],
      ["Lars Jacobsen", "RB", 76],
      ["Daniel Agger", "CB", 83],
      ["Simon Kjær", "CB", 81],
      ["Per Kroldrup", "CB", 75],
      ["Christian Poulsen", "CDM", 80],
      ["William Kvist", "CDM", 76],
      ["Thomas Kahlenberg", ["CM", "CAM"], 77],
      ["Christian Eriksen", ["CAM", "LW"], 79],
      ["Dennis Rommedahl", "RW", 78],
      ["Martin Jørgensen", ["RW", "RM"], 74],
      ["Jakob Poulsen", "CM", 73],
      ["Jesper Grønkjær", "RW", 72],
      ["Jon Dahl Tomasson", ["ST", "CF"], 79],
      ["Nicklas Bendtner", "ST", 80],
      ["Søren Larsen", "ST", 73],
      ["Michael Silberbauer", "CM", 72],
      ["Mikkel Beckmann", "ST", 71],
      ["Patrick Mtiliga", "CB", 73],
      ["Mikael Antonsson", "CB", 72],
    ],
    Japan: [
      ["Eiji Kawashima", "GK", 82],
      ["Seigo Narazaki", "GK", 74],
      ["Yoshikatsu Kawaguchi", "GK", 71],
      ["Atsuto Uchida", "RB", 78],
      ["Yuto Nagatomo", "LB", 80],
      ["Yuji Nakazawa", "CB", 82],
      ["Marcus Tulio Tanaka", "CB", 78],
      ["Yuichi Komano", ["RB", "CB"], 76],
      ["Makoto Hasebe", "CDM", 83],
      ["Yasuhito Endō", "CM", 84],
      ["Keisuke Honda", ["CAM", "CM"], 88],
      ["Shunsuke Nakamura", ["LW", "CAM"], 80],
      ["Daisuke Matsui", ["RM", "RW"], 79],
      ["Yoshito Okubo", ["ST", "CF"], 77],
      ["Shinji Okazaki", ["ST", "CF"], 79],
      ["Kengo Nakamura", "CM", 75],
      ["Junichi Inamoto", "CM", 74],
      ["Ryo Miyaichi", "LW", 71],
      ["Takayuki Morimoto", "ST", 73],
      ["Ryoichi Maeda", "ST", 74],
      ["Yuki Abe", "CDM", 73],
      ["Kosuke Kimura", "LB", 72],
      ["Naoki Matsuda", "CB", 74],
    ],
    Cameroon: [
      ["Souleymanou Hamidou", "GK", 75],
      ["Idriss Carlos Kameni", "GK", 78],
      ["Charles Itandje", "GK", 72],
      ["Rigobert Song", "CB", 78],
      ["Aurélien Chedjou", "CB", 77],
      ["Nicolas N'Koulou", "CB", 79],
      ["Benoît Assou-Ekotto", "LB", 80],
      ["Sébastien Bassong", "CB", 78],
      ["Stéphane Mbia", ["CDM", "CB"], 80],
      ["Alexandre Song", "CDM", 82],
      ["Jean II Makoun", "CM", 79],
      ["Joël Matip", "CB", 75],
      ["Geremi", ["RB", "RM"], 76],
      ["Landry N'Guemo", "CDM", 77],
      ["Achille Webo", ["ST", "RW"], 76],
      ["Samuel Eto'o", "ST", 90],
      ["Mohamadou Idrissou", "ST", 74],
      ["Vincent Aboubakar", "ST", 72],
      ["Eric Choupo-Moting", ["LW", "CF"], 73],
      ["Guy N'dy Assembé", "GK", 71],
      ["Gaëtan Bong", "LB", 73],
      ["Enoh Eyong", ["CM", "CDM"], 74],
      ["Georges Mandjeck", "CM", 73],
    ],
    Italy: [
      ["Gianluigi Buffon", "GK", 88],
      ["Federico Marchetti", "GK", 74],
      ["Morgan De Sanctis", "GK", 77],
      ["Christian Maggio", "RB", 80],
      ["Domenico Criscito", "LB", 78],
      ["Giorgio Chiellini", "CB", 85],
      ["Fabio Cannavaro", "CB", 82],
      ["Salvatore Bocchetti", "CB", 73],
      ["Gianluca Zambrotta", ["RB", "RWB"], 79],
      ["Leonardo Bonucci", "CB", 76],
      ["Daniele De Rossi", "CDM", 86],
      ["Simone Pepe", "RM", 74],
      ["Gennaro Gattuso", "CDM", 81],
      ["Claudio Marchisio", "CM", 80],
      ["Mauro Camoranesi", "CM", 75],
      ["Angelo Palombo", "CDM", 72],
      ["Andrea Pirlo", "CM", 84],
      ["Riccardo Montolivo", "CM", 79],
      ["Vincenzo Iaquinta", "ST", 76],
      ["Antonio Di Natale", "ST", 82],
      ["Alberto Gilardino", "ST", 79],
      ["Fabio Quagliarella", "CF", 76],
      ["Giampaolo Pazzini", "ST", 74],
    ],
    Paraguay: [
      ["Justo Villar", "GK", 82],
      ["Diego Barreto", "GK", 72],
      ["Aldo Bobadilla", "GK", 71],
      ["Dario Veron", "RB", 76],
      ["Claudio Morel", "LB", 77],
      ["Denis Caniza", "RB", 73],
      ["Julio Cesar Caceres", "CB", 79],
      ["Paulo Da Silva", "CB", 80],
      ["Aureliano Torres", "LB", 74],
      ["Antolin Alcaraz", "CB", 78],
      ["Carlos Bonet", "CM", 74],
      ["Edgar Barreto", "CM", 76],
      ["Jonathan Santana", "CM", 77],
      ["Enrique Vera", "CDM", 75],
      ["Victor Caceres", "CM", 73],
      ["Cristian Riveros", "CM", 78],
      ["Nestor Ortigoza", "CM", 72],
      ["Oscar Cardozo", "ST", 82],
      ["Roque Santa Cruz", "ST", 83],
      ["Edgar Benitez", "RW", 76],
      ["Nelson Valdez", "ST", 78],
      ["Lucas Barrios", "ST", 80],
      ["Rodolfo Gamarra", "CF", 70],
    ],
    "New Zealand": [
      ["Mark Paston", "GK", 73],
      ["Glen Moss", "GK", 72],
      ["James Bannatyne", "GK", 70],
      ["Ben Sigmund", "CB", 71],
      ["Tony Lochhead", "LB", 72],
      ["Winston Reid", "CB", 75],
      ["Ivan Vicelich", "CB", 73],
      ["Ryan Nelsen", "CB", 81],
      ["Andy Boyens", "CB", 71],
      ["Tommy Smith", "RB", 74],
      ["Simon Elliott", "CM", 73],
      ["Tim Brown", "CM", 70],
      ["Leo Bertos", "RM", 73],
      ["Andy Barron", "CM", 70],
      ["Michael McGlinchey", "LM", 73],
      ["Aaron Clapham", "LM", 70],
      ["David Mulligan", "CM", 71],
      ["Jeremy Christie", "CM", 72],
      ["Jeremy Brockie", "RW", 71],
      ["Shane Smeltz", "ST", 76],
      ["Chris Killen", "ST", 74],
      ["Rory Fallon", "ST", 73],
      ["Chris Wood", "ST", 72],
    ],
    Slovakia: [
      ["Jan Mucha", "GK", 79],
      ["Dusan Pernis", "GK", 71],
      ["Dusan Kuciak", "GK", 72],
      ["Peter Pekarik", "RB", 76],
      ["Martin Skrtel", "CB", 84],
      ["Marek Cech", "CB", 77],
      ["Radoslav Zabavnik", "LB", 75],
      ["Jan Durica", "CB", 76],
      ["Kornel Salata", "CB", 72],
      ["Martin Petras", "LB", 71],
      ["Zdenko Strba", "CDM", 73],
      ["Vladimir Weiss", "RW", 78],
      ["Jan Kozak", "CM", 72],
      ["Marek Sapara", "CM", 74],
      ["Miroslav Stoch", "LW", 76],
      ["Marek Hamsik", "CAM", 85],
      ["Juraj Kucka", "CM", 77],
      ["Kamil Kopunek", "CM", 72],
      ["Stanislav Sestak", "ST", 76],
      ["Robert Vittek", "ST", 80],
      ["Filip Holosko", "RW", 75],
      ["Martin Jakubko", "ST", 72],
      ["Erik Jendrisek", "ST", 73],
    ],
    Brazil: [
      ["Julio Cesar", "GK", 88],
      ["Doni", "GK", 78],
      ["Heurelho Gomes", "GK", 76],
      ["Maicon", "RB", 90],
      ["Dani Alves", "RB", 86],
      ["Lucio", "CB", 85],
      ["Juan", "CB", 83],
      ["Luisao", "CB", 80],
      ["Thiago Silva", "CB", 82],
      ["Gilberto", "LB", 75],
      ["Michel Bastos", ["LB", "LM"], 79],
      ["Felipe Melo", "CDM", 80],
      ["Gilberto Silva", "CDM", 79],
      ["Josue", "CM", 74],
      ["Ramires", "CM", 77],
      ["Kleberson", "CM", 72],
      ["Elano", ["CM", "CAM"], 78],
      ["Kaka", "CAM", 88],
      ["Julio Baptista", ["CM", "CF"], 74],
      ["Robinho", ["LW", "CF"], 84],
      ["Luis Fabiano", "ST", 87],
      ["Nilmar", "ST", 76],
      ["Grafite", "ST", 73],
    ],
    Portugal: [
      ["Eduardo", "GK", 76],
      ["Beto", "GK", 75],
      ["Daniel Fernandes", "GK", 72],
      ["Ricardo Carvalho", "CB", 85],
      ["Pepe", "CB", 86],
      ["Bruno Alves", "CB", 82],
      ["Rolando", "CB", 76],
      ["Ricardo Costa", "CB", 74],
      ["Paulo Ferreira", "RB", 77],
      ["Miguel", "RB", 74],
      ["Fabio Coentrao", "LB", 81],
      ["Duda", "LB", 73],
      ["Raul Meireles", ["CM", "CDM"], 83],
      ["Tiago", "CDM", 80],
      ["Miguel Veloso", "CM", 78],
      ["Pedro Mendes", "CM", 72],
      ["Deco", ["CAM", "CM"], 79],
      ["Cristiano Ronaldo", "LW", 93],
      ["Simao Sabrosa", "RW", 78],
      ["Nani", "LW", 80],
      ["Danny", ["LW", "CAM"], 77],
      ["Hugo Almeida", "ST", 77],
      ["Liedson", "ST", 74],
      ["Ruben Amorim", "CM", 70],
    ],
    "Ivory Coast": [
      ["Boubacar Barry", "GK", 78],
      ["Aristide Zogbo", "GK", 70],
      ["Daniel Yeboah", "GK", 70],
      ["Kolo Toure", "CB", 84],
      ["Souleymane Bamba", "CB", 76],
      ["Guy Demel", "RB", 76],
      ["Emmanuel Eboue", ["RB", "RM"], 79],
      ["Siaka Tiene", "LB", 74],
      ["Arthur Boka", "LB", 75],
      ["Steve Gohouri", "CB", 72],
      ["Benjamin Brou Angoua", ["CB", "RB"], 71],
      ["Yaya Toure", "CM", 88],
      ["Didier Zokora", "CDM", 80],
      ["Cheik Ismael Tiote", "CDM", 79],
      ["Jean-Jacques Gosso", "CM", 73],
      ["Abdelkader Keita", ["LM", "CAM"], 77],
      ["Emmanuel Kone", "CM", 70],
      ["Gervais Yao Kouassi", ["LW", "LM"], 76],
      ["Christian Koffi Ndri", ["RM", "RW"], 73],
      ["Didier Drogba", "ST", 89],
      ["Salomon Kalou", ["LW", "ST"], 78],
      ["Aruna Dindane", "ST", 74],
      ["Seydou Doumbia", "ST", 75],
    ],
    "North Korea": [
      ["Ri Myong-Guk", "GK", 74],
      ["Kim Myong-Gil", "GK", 70],
      ["Kim Myong-Won", "GK", 70],
      ["Cha Jong-Hyok", "CB", 73],
      ["Ri Jun-Il", "LB", 71],
      ["Ri Kwang-Chon", "CB", 72],
      ["Ri Kwang-Hyok", "RB", 70],
      ["Pak Chol-Jin", ["CB", "RB"], 71],
      ["Pak Nam-Chol", ["RB", "CM"], 72],
      ["Nam Song-Chol", "CB", 70],
      ["Ahn Young-Hak", "CM", 77],
      ["Ji Yun-Nam", ["CDM", "LB"], 73],
      ["Mun In-Guk", "CM", 72],
      ["Kim Kyong-Il", "CM", 70],
      ["Kim Yong-Jun", "CM", 70],
      ["Pak Sung-Hyok", "CM", 71],
      ["Ri Chol-Myong", "CM", 71],
      ["An Chol-Hyok", ["LW", "ST"], 71],
      ["Choe Kum-Chol", "ST", 72],
      ["Hong Yong-Jo", "ST", 76],
      ["Jong Tae-Se", "ST", 78],
      ["Kim Kum-Il", ["CM", "ST"], 70],
    ],
    Spain: [
      ["Iker Casillas", "GK", 93],
      ["Victor Valdes", "GK", 80],
      ["Pepe Reina", "GK", 82],
      ["Sergio Ramos", ["RB", "CB"], 90],
      ["Alvaro Arbeloa", "RB", 81],
      ["Carles Puyol", "CB", 88],
      ["Gerard Pique", "CB", 87],
      ["Carlos Marchena", "CB", 79],
      ["Raul Albiol", "CB", 78],
      ["Joan Capdevila", "LB", 82],
      ["Xavi", "CM", 94],
      ["Andres Iniesta", "CM", 93],
      ["Xabi Alonso", "CDM", 91],
      ["Sergio Busquets", "CDM", 88],
      ["Cesc Fabregas", ["CM", "CF"], 86],
      ["David Silva", "CAM", 85],
      ["Jesus Navas", "RW", 81],
      ["Javi Martinez", "CDM", 75],
      ["David Villa", "ST", 92],
      ["Fernando Torres", "ST", 84],
      ["Fernando Llorente", "ST", 74],
      ["Pedro", "RW", 79],
      ["Juan Mata", "CAM", 76],
    ],
    Switzerland: [
      ["Diego Benaglio", "GK", 82],
      ["Marco Woelfli", "GK", 70],
      ["Johnny Leoni", "GK", 70],
      ["Stephan Lichtsteiner", "RB", 82],
      ["Ludovic Magnin", "LB", 74],
      ["Philippe Senderos", "CB", 75],
      ["Steve Von Bergen", "CB", 77],
      ["Stephane Grichting", "CB", 76],
      ["Reto Ziegler", ["LB", "CB"], 73],
      ["Mario Eggimann", "CB", 72],
      ["Gokhan Inler", "CDM", 81],
      ["Gelson Fernandes", "CM", 79],
      ["Tranquillo Barnetta", ["LM", "CAM"], 78],
      ["Valon Behrami", "CM", 76],
      ["Benjamin Huggel", "CM", 73],
      ["Hakan Yakin", "CAM", 74],
      ["Pirmin Schwegler", "CM", 72],
      ["Marco Padalino", "CM", 71],
      ["Xherdan Shaqiri", "RW", 74],
      ["Alexander Frei", "ST", 76],
      ["Blaise Nkufo", "ST", 77],
      ["Eren Derdiyok", "ST", 75],
      ["Albert Bunjaku", "ST", 70],
    ],
    Chile: [
      ["Claudio Bravo", "GK", 85],
      ["Miguel Pinto", "GK", 72],
      ["Luis Marin", "GK", 70],
      ["Pablo Contreras", "CB", 77],
      ["Waldo Ponce", "CB", 75],
      ["Ismael Fuentes", "RB", 73],
      ["Mauricio Isla", "RB", 79],
      ["Gary Medel", ["CB", "CDM"], 82],
      ["Gonzalo Jara", "LB", 76],
      ["Arturo Vidal", ["CM", "CDM"], 85],
      ["Jorge Valdivia", "CAM", 80],
      ["Matias Fernandez", "CM", 78],
      ["Carlos Carmona", "CM", 75],
      ["Rodrigo Tello", "LM", 74],
      ["Rodrigo Millar", "CM", 72],
      ["Marco Estrada", "CM", 71],
      ["Gonzalo Fierro", "CDM", 71],
      ["Alexis Sanchez", ["RW", "LW"], 84],
      ["Humberto Suazo", "ST", 80],
      ["Mark Gonzalez", ["LW", "LM"], 76],
      ["Jean Beausejour", ["LB", "LW"], 77],
      ["Fabian Orellana", "RW", 74],
      ["Esteban Paredes", "ST", 73],
    ],
    Honduras: [
      ["Noel Valladares", "GK", 77],
      ["Ricardo Canales", "GK", 70],
      ["Donis Escober", "GK", 70],
      ["Maynor Figueroa", "LB", 78],
      ["Osman Chavez", "CB", 75],
      ["Victor Bernardez", "CB", 74],
      ["Johnny Palacios", "CB", 73],
      ["Emilio Izaguirre", "LB", 77],
      ["Sergio Mendoza", "RB", 72],
      ["Mauricio Sabillon", "RB", 71],
      ["Oscar Boniek Garcia", ["RB", "RM"], 74],
      ["Wilson Palacios", "CM", 80],
      ["Hendry Thomas", "CDM", 76],
      ["Amado Guevara", "CM", 74],
      ["Edgar Alvarez", "CM", 73],
      ["Ramon Nunez", ["CAM", "LM"], 72],
      ["Roger Espinoza", "CM", 73],
      ["Danilo Turcios", "CM", 71],
      ["David Suazo", "ST", 76],
      ["Carlos Pavon", "ST", 72],
      ["Jerry Palacios", "ST", 73],
      ["Walter Martinez", "LW", 71],
      ["George Welcome", "ST", 70],
    ],
  },
  2014: {
    Brazil: [
      ["Jefferson", "GK", 76],
      ["Dani Alves", "RB", 81],
      ["Thiago Silva", "CB", 88],
      ["David Luiz", "CB", 84],
      ["Fernandinho", "CM", 79],
      ["Marcelo", "LB", 84],
      ["Hulk", "RW", 80],
      ["Paulinho", "CM", 78],
      ["Fred", "ST", 74],
      ["Neymar", "LW", 88],
      ["Oscar", "CAM", 85],
      ["Julio Cesar", "GK", 82],
      ["Dante", "CB", 74],
      ["Maxwell", "LB", 73],
      ["Henrique", "CB", 72],
      ["Ramires", "CM", 77],
      ["Luiz Gustavo", "CDM", 81],
      ["Hernanes", "CM", 74],
      ["Willian", "RW", 78],
      ["Bernard", "LW", 74],
      ["Jo", "ST", 72],
      ["Victor", "GK", 72],
      ["Maicon", "RB", 78],
    ],
    Croatia: [
      ["Pletikosa", "GK", 77],
      ["Vrsaljko", "RB", 75],
      ["Pranjic", "LB", 73],
      ["Perisic", "LW", 79],
      ["Corluka", "CB", 77],
      ["Lovren", "CB", 78],
      ["Rakitic", "CM", 82],
      ["Vukojevic", "CM", 72],
      ["Jelavic", "ST", 75],
      ["Modric", "CM", 84],
      ["Srna", "RB", 79],
      ["Zelenika", "GK", 71],
      ["Schildenfeld", "CB", 72],
      ["Brozovic", "CM", 73],
      ["Badelj", "CDM", 76],
      ["Rebic", "ST", 72],
      ["Mandzukic", "ST", 81],
      ["Olic", "LW", 76],
      ["Sammir", "CAM", 71],
      ["Kovacic", "CM", 75],
      ["Vida", "CB", 73],
      ["Eduardo", "ST", 72],
      ["Subasic", "GK", 74],
    ],
    Mexico: [
      ["Corona", "GK", 74],
      ["F.J. Rodriguez", "CB", 78],
      ["Salcido", "LB", 76],
      ["Marquez", "CB", 81],
      ["Reyes", "CB", 76],
      ["H. Herrera", "CM", 79],
      ["Layun", ["RB", "LM"], 78],
      ["Fabian", "CM", 77],
      ["Jimenez", "ST", 75],
      ["dos Santos", "CAM", 80],
      ["Pulido", "ST", 73],
      ["Talavera", "GK", 72],
      ["Ochoa", "GK", 85],
      ["Hernandez", "ST", 77],
      ["Moreno", "CB", 78],
      ["Ponce", "ST", 71],
      ["Brizuela", "CM", 71],
      ["Guardado", "LM", 80],
      ["Peralta", "ST", 78],
      ["Aquino", "CM", 73],
      ["Pena", "CM", 75],
      ["Aguilar", "RB", 77],
      ["Vazquez", "CM", 72],
    ],
    Cameroon: [
      ["Feudjou", "GK", 70],
      ["Assou-Ekotto", "LB", 74],
      ["Nkoulou", "CB", 76],
      ["Djeugoue", "CB", 71],
      ["Nounkeu", "CB", 71],
      ["Song", "CDM", 74],
      ["N'Guemo", "CM", 72],
      ["Moukandjo", "ST", 72],
      ["Eto'o", "ST", 78],
      ["Aboubakar", "ST", 73],
      ["Makoun", "CM", 72],
      ["Bedimo", "LB", 73],
      ["Choupo-Moting", "CF", 74],
      ["Chedjou", "CB", 73],
      ["Webo", "ST", 71],
      ["Itandje", "GK", 70],
      ["Mbia", "CDM", 74],
      ["Enoh", "CM", 72],
      ["Olinga", "LW", 70],
      ["Salli", "CM", 70],
      ["Matip", "CB", 75],
      ["Nyom", "RB", 71],
      ["Ndjock", "GK", 70],
    ],
    Spain: [
      ["Casillas", "GK", 76],
      ["Albiol", "CB", 75],
      ["Pique", "CB", 77],
      ["Javi Martinez", "CDM", 76],
      ["Juanfran", "RB", 75],
      ["Iniesta", "CM", 82],
      ["Villa", "ST", 77],
      ["Xavi", "CM", 79],
      ["Torres", "ST", 74],
      ["Fabregas", "CAM", 79],
      ["Pedro", "RW", 76],
      ["De Gea", "GK", 78],
      ["Mata", "CAM", 77],
      ["Xabi Alonso", "CM", 79],
      ["Ramos", "CB", 81],
      ["Busquets", "CDM", 81],
      ["Koke", "CM", 77],
      ["Jordi Alba", "LB", 79],
      ["Diego Costa", "ST", 75],
      ["Cazorla", "LM", 77],
      ["David Silva", "CAM", 81],
      ["Azpilicueta", "RB", 76],
      ["Reina", "GK", 73],
    ],
    Netherlands: [
      ["Cillessen", "GK", 80],
      ["Vlaar", "CB", 85],
      ["de Vrij", "CB", 86],
      ["Martins Indi", "CB", 78],
      ["Blind", "LB", 83],
      ["de Jong", "CDM", 80],
      ["Janmaat", "RB", 79],
      ["de Guzman", "CM", 75],
      ["van Persie", "ST", 87],
      ["Sneijder", "CAM", 83],
      ["Robben", "LW", 91],
      ["Verhaegh", "RB", 72],
      ["Veltman", "CB", 74],
      ["Kongolo", "LB", 72],
      ["Kuyt", ["RWB", "LWB"], 78],
      ["Clasie", "CM", 73],
      ["Lens", "RW", 75],
      ["Fer", "CM", 74],
      ["Huntelaar", "ST", 78],
      ["Wijnaldum", "CM", 76],
      ["Depay", "LW", 78],
      ["Vorm", "GK", 73],
      ["Krul", "GK", 77],
    ],
    Chile: [
      ["Bravo", "GK", 81],
      ["Mena", "LB", 76],
      ["Albornoz", "LB", 73],
      ["Isla", "RWB", 79],
      ["F. Silva", "CM", 74],
      ["Carmona", "CM", 76],
      ["Sanchez", ["LW", "ST"], 85],
      ["Vidal", "CM", 84],
      ["Pinilla", "ST", 76],
      ["Valdivia", "CAM", 77],
      ["Vargas", "LW", 81],
      ["Toselli", "GK", 72],
      ["Rojas", "CB", 73],
      ["Orellana", "LW", 74],
      ["Beausejour", "LWB", 77],
      ["Gutierrez", "CM", 73],
      ["Medel", ["CB", "CDM"], 81],
      ["Jara", "CB", 78],
      ["Fuenzalida", "RM", 74],
      ["Aranguiz", "CM", 80],
      ["Diaz", "CDM", 78],
      ["Paredes", "ST", 73],
      ["Herrera", "GK", 71],
    ],
    Australia: [
      ["Ryan", "GK", 75],
      ["Franjic", "RB", 72],
      ["Davidson", "LB", 73],
      ["Cahill", "ST", 80],
      ["Milligan", "CDM", 75],
      ["Spiranovic", "CB", 74],
      ["Leckie", "RW", 76],
      ["Wright", "CB", 72],
      ["Taggart", "ST", 71],
      ["Halloran", "CM", 71],
      ["Oar", "LM", 72],
      ["Langerak", "GK", 71],
      ["Bozanic", "CM", 72],
      ["Troisi", "CAM", 73],
      ["Jedinak", "CDM", 78],
      ["Holland", "CM", 72],
      ["McKay", "LM", 73],
      ["Galekovic", "GK", 70],
      ["McGowan", "CB", 72],
      ["Vidosic", "CAM", 70],
      ["Luongo", "CM", 72],
      ["Wilkinson", "CB", 73],
      ["Bresciano", "CAM", 74],
    ],
    Colombia: [
      ["Ospina", "GK", 82],
      ["Zapata", "CB", 78],
      ["Yepes", "CB", 79],
      ["Arias", "RB", 78],
      ["Carbonero", "RW", 74],
      ["C. Sanchez", "CDM", 80],
      ["Armero", "LB", 78],
      ["Aguilar", "CDM", 76],
      ["Gutierrez", "ST", 77],
      ["James Rodriguez", "CAM", 91],
      ["Cuadrado", "RW", 84],
      ["Vargas", "GK", 72],
      ["Guarin", "CM", 79],
      ["Ibarbo", "ST", 74],
      ["Mejia", "CB", 74],
      ["Balanta", "CM", 72],
      ["Bacca", "ST", 77],
      ["Zuniga", "RB", 77],
      ["Adrian Ramos", "ST", 75],
      ["Quintero", "CAM", 77],
      ["Jackson Martinez", "ST", 78],
      ["Mondragon", "GK", 73],
      ["Valdes", "CB", 73],
    ],
    Greece: [
      ["Karnezis", "GK", 78],
      ["Maniatis", "CDM", 75],
      ["Tzavellas", "LB", 74],
      ["Manolas", "CB", 78],
      ["Moras", "CB", 73],
      ["Tziolis", "CM", 74],
      ["Samaras", ["ST", "LW"], 78],
      ["Kone", "CM", 75],
      ["Mitroglou", "ST", 75],
      ["Karagounis", "CM", 77],
      ["Vyntra", "RB", 73],
      ["Glykos", "GK", 70],
      ["Kapino", "GK", 70],
      ["Salpingidis", "RW", 75],
      ["Torosidis", "RB", 77],
      ["Christodoulopoulos", "LM", 74],
      ["Gekas", "ST", 74],
      ["Fetfatzidis", "RW", 73],
      ["Papastathopoulos", "CB", 78],
      ["Holebas", "LB", 76],
      ["Katsouranis", "CDM", 75],
      ["Samaris", "CDM", 74],
      ["Tachtsidis", "CM", 72],
    ],
    "Ivory Coast": [
      ["Barry", "GK", 74],
      ["Viera", "RB", 73],
      ["Boka", "LB", 73],
      ["Kolo Toure", "CB", 77],
      ["Zokora", "CDM", 74],
      ["Bolly", "ST", 71],
      ["Akpa Akpro", "ST", 70],
      ["Kalou", "LW", 78],
      ["Tiote", "CDM", 76],
      ["Gervinho", "LW", 80],
      ["Drogba", "ST", 78],
      ["Bony", "ST", 78],
      ["Ya Konan", "ST", 71],
      ["Diomande", "CM", 72],
      ["Gradel", "RW", 73],
      ["Gbohouo", "GK", 71],
      ["Aurier", "RB", 79],
      ["Djakpa", "LB", 71],
      ["Yaya Toure", "CM", 82],
      ["Serey Die", "CDM", 75],
      ["Sio", "ST", 71],
      ["Bamba", "CB", 73],
      ["Mande", "GK", 70],
    ],
    Japan: [
      ["Kawashima", "GK", 75],
      ["Uchida", "RB", 77],
      ["Sakai G.", "RB", 73],
      ["Honda", "CAM", 80],
      ["Nagatomo", "LB", 78],
      ["Morishige", "CB", 73],
      ["Endo", "CDM", 77],
      ["Kiyotake", "CAM", 74],
      ["Okazaki", "ST", 78],
      ["Kagawa", "CAM", 77],
      ["Kakitani", "ST", 73],
      ["Nishikawa", "GK", 71],
      ["Okubo", "ST", 75],
      ["Aoyama", "CM", 73],
      ["Konno", "CB", 73],
      ["Yamaguchi", "CM", 74],
      ["Hasebe", "CDM", 77],
      ["Osako", "ST", 72],
      ["Inoha", "CB", 71],
      ["Saito", "LW", 72],
      ["Sakai H.", "LB", 73],
      ["Yoshida", "CB", 77],
      ["Gonda", "GK", 71],
    ],
    Uruguay: [
      ["Muslera", "GK", 80],
      ["Lugano", "CB", 76],
      ["Godin", "CB", 84],
      ["Fucile", "LB", 75],
      ["Gargano", "CM", 73],
      ["A. Pereira", "CM", 74],
      ["C. Rodriguez", "LM", 77],
      ["A. Hernandez", "ST", 73],
      ["Suarez", "ST", 82],
      ["Forlan", "ST", 76],
      ["Stuani", "ST", 74],
      ["R. Munoz", "GK", 71],
      ["Gimenez", "CB", 80],
      ["Lodeiro", "LM", 75],
      ["D. Perez", "CDM", 75],
      ["Maxi Pereira", "RB", 77],
      ["Arevalo Rios", "CDM", 78],
      ["G. Ramirez", "CAM", 76],
      ["Coates", "CB", 73],
      ["A. Gonzalez", "CM", 73],
      ["Cavani", "ST", 83],
      ["Caceres", "RB", 78],
      ["M. Silva", "GK", 71],
    ],
    "Costa Rica": [
      ["Navas", "GK", 87],
      ["Acosta", "RB", 77],
      ["G. Gonzalez", "CB", 78],
      ["Umana", "CB", 76],
      ["Borges", "CDM", 79],
      ["Duarte", "CB", 77],
      ["Bolanos", "CAM", 78],
      ["Myrie", "RB", 76],
      ["Campbell", "CF", 80],
      ["Ruiz", "CAM", 81],
      ["Barrantes", "CM", 74],
      ["Francis", "RWB", 77],
      ["Granados", "CM", 73],
      ["Brenes", "ST", 72],
      ["Diaz", "CB", 79],
      ["Gamboa", "RB", 75],
      ["Tejeda", "CM", 73],
      ["Pemberton", "GK", 71],
      ["Miller", "LB", 75],
      ["Calvo", "CB", 74],
      ["Urena", "ST", 74],
      ["Cubero", "LWB", 75],
      ["Cambronero", "GK", 71],
    ],
    England: [
      ["Hart", "GK", 76],
      ["G. Johnson", "RB", 75],
      ["Baines", "LB", 76],
      ["Gerrard", "CM", 80],
      ["Cahill", "CB", 78],
      ["Jagielka", "CB", 75],
      ["Wilshere", "CM", 75],
      ["Lampard", "CM", 76],
      ["Sturridge", "ST", 78],
      ["Rooney", "ST", 79],
      ["Welbeck", "LW", 75],
      ["Smalling", "CB", 73],
      ["Foster", "GK", 72],
      ["Henderson", "CM", 77],
      ["Oxlade-Chamberlain", "RW", 74],
      ["Jones", "CB", 73],
      ["Milner", "RM", 75],
      ["Lambert", "ST", 73],
      ["Sterling", "RW", 78],
      ["Lallana", "CAM", 75],
      ["Barkley", "CAM", 74],
      ["Forster", "GK", 71],
      ["Shaw", "LB", 73],
    ],
    Italy: [
      ["Buffon", "GK", 81],
      ["De Sciglio", "LB", 75],
      ["Chiellini", "CB", 81],
      ["Darmian", "RB", 75],
      ["Thiago Motta", "CDM", 75],
      ["Candreva", "RM", 76],
      ["Abate", "RB", 74],
      ["Marchisio", "CM", 78],
      ["Balotelli", "ST", 78],
      ["Cassano", "CF", 74],
      ["Cerci", "RW", 73],
      ["Sirigu", "GK", 73],
      ["Perin", "GK", 71],
      ["Aquilani", "CM", 73],
      ["Barzagli", "CB", 79],
      ["De Rossi", "CDM", 79],
      ["Immobile", "ST", 74],
      ["Parolo", "CM", 75],
      ["Bonucci", "CB", 80],
      ["Paletta", "CB", 72],
      ["Pirlo", "CM", 82],
      ["Insigne", "LW", 74],
      ["Verratti", "CM", 76],
    ],
    Switzerland: [
      ["Benaglio", "GK", 79],
      ["Lichtsteiner", "RB", 80],
      ["Ziegler", "LB", 73],
      ["Senderos", "CB", 74],
      ["von Bergen", "CB", 75],
      ["Lang", "RB", 74],
      ["Barnetta", "CM", 75],
      ["Inler", "CDM", 79],
      ["Seferovic", "ST", 75],
      ["Xhaka", "CM", 79],
      ["Behrami", "CDM", 77],
      ["Sommer", "GK", 73],
      ["R. Rodriguez", "LB", 81],
      ["Stocker", "LM", 73],
      ["Dzemaili", "CM", 75],
      ["G. Fernandes", "CM", 74],
      ["Gavranovic", "ST", 72],
      ["Mehmedi", "LW", 76],
      ["Drmic", "ST", 74],
      ["Djourou", "CB", 76],
      ["Burki", "GK", 71],
      ["Schar", "CB", 77],
      ["Shaqiri", "RW", 83],
    ],
    Ecuador: [
      ["Banguera", "GK", 73],
      ["Guagua", "CB", 73],
      ["Erazo", "CB", 74],
      ["Paredes", "CB", 73],
      ["Ibarra", "RM", 73],
      ["Noboa", "CM", 76],
      ["Montero", "LW", 76],
      ["Mendez", "CM", 74],
      ["Rojas", "ST", 73],
      ["W. Ayovi", "LB", 75],
      ["Caicedo", "ST", 75],
      ["Bone", "GK", 71],
      ["E. Valencia", "ST", 80],
      ["Minda", "CM", 72],
      ["Arroyo", "RM", 74],
      ["A. Valencia", "RM", 78],
      ["J. Ayovi", "ST", 72],
      ["Bagui", "RB", 72],
      ["Saritama", "CM", 71],
      ["F. Martinez", "CM", 72],
      ["Achilier", "CB", 74],
      ["Dominguez", "GK", 71],
      ["Gruezo", "CDM", 74],
    ],
    France: [
      ["Lloris", "GK", 84],
      ["Debuchy", "RB", 78],
      ["Evra", "LB", 79],
      ["Varane", "CB", 82],
      ["Sakho", "CB", 78],
      ["Cabaye", "CM", 80],
      ["Cabella", "RW", 72],
      ["Valbuena", "CAM", 81],
      ["Giroud", "ST", 77],
      ["Benzema", "ST", 86],
      ["Griezmann", "LW", 80],
      ["Mavuba", "CM", 72],
      ["Mangala", "CB", 73],
      ["Matuidi", "CM", 81],
      ["Sagna", "RB", 76],
      ["Ruffier", "GK", 72],
      ["Digne", "LB", 73],
      ["Sissoko", "CM", 76],
      ["Pogba", "CM", 84],
      ["Remy", "ST", 74],
      ["Koscielny", "CB", 77],
      ["Schneiderlin", "CDM", 74],
      ["Landreau", "GK", 71],
    ],
    Honduras: [
      ["Lopez", "GK", 74],
      ["O. Chavez", "RB", 72],
      ["Figueroa", "CB", 75],
      ["Montes", "CB", 72],
      ["Bernardez", "CB", 74],
      ["J.C. Garcia", "RB", 72],
      ["Izaguirre", "LB", 76],
      ["W. Palacios", "CDM", 75],
      ["J. Palacios", "ST", 71],
      ["M. Martinez", "CDM", 74],
      ["Bengtson", "ST", 72],
      ["Delgado", "CM", 72],
      ["Costly", "ST", 74],
      ["Boniek Garcia", "RM", 75],
      ["Espinoza", "CM", 74],
      ["R. Martinez", "ST", 72],
      ["Najar", "RW", 73],
      ["Valladares", "GK", 75],
      ["Garrido", "CM", 71],
      ["Claros", "CDM", 73],
      ["Beckeles", "LB", 72],
      ["Escober", "GK", 70],
      ["M. Chavez", "CM", 70],
    ],
    Argentina: [
      ["Romero", "GK", 84],
      ["Garay", "CB", 80],
      ["Campagnaro", "CB", 74],
      ["Zabaleta", "RB", 82],
      ["Gago", "CM", 77],
      ["Biglia", "CM", 76],
      ["Di Maria", "RM", 87],
      ["E. Perez", "CM", 76],
      ["Higuain", "ST", 80],
      ["Messi", "CAM", 92],
      ["Maxi Rodriguez", "RM", 75],
      ["Orion", "GK", 72],
      ["A. Fernandez", "CM", 74],
      ["Mascherano", "CDM", 89],
      ["Demichelis", "CB", 78],
      ["Rojo", "CB", 85],
      ["F. Fernandez", "CB", 75],
      ["Palacio", "ST", 78],
      ["R. Alvarez", "CM", 75],
      ["Aguero", "ST", 80],
      ["Andujar", "GK", 72],
      ["Lavezzi", "LW", 80],
      ["Basanta", "CB", 73],
    ],
    "Bosnia and Herzegovina": [
      ["Begovic", "GK", 79],
      ["Vrsajevic", "RB", 74],
      ["Bicakcic", "CB", 73],
      ["Spahic", "CB", 77],
      ["Kolasinac", "LB", 75],
      ["Vranjes", "CB", 72],
      ["Besic", "CDM", 75],
      ["Pjanic", "CAM", 80],
      ["Ibisevic", "ST", 75],
      ["Misimovic", "CAM", 76],
      ["Dzeko", "ST", 81],
      ["Fejzic", "GK", 70],
      ["Mujdza", "RB", 72],
      ["T-S. Susic", "CM", 73],
      ["Sunjic", "CB", 72],
      ["Lulic", "LM", 75],
      ["Ibricic", "CM", 71],
      ["Medunjanin", "CM", 75],
      ["Visca", "RW", 73],
      ["Hajrovic", "LW", 73],
      ["Hadzic", "CM", 70],
      ["Avdukic", "GK", 70],
      ["Salihovic", "CM", 74],
    ],
    Iran: [
      ["R. Ahmadi", "GK", 73],
      ["Heydari", "CB", 73],
      ["Hajsafi", "LB", 76],
      ["Hosseini", "CB", 74],
      ["Sadeghi", "CB", 73],
      ["Nekounam", "CDM", 77],
      ["Shojaei", "CAM", 75],
      ["R. Haghighi", "CB", 73],
      ["Jahanbakhsh", "RW", 74],
      ["Ansarifard", "ST", 73],
      ["Haddadifar", "CM", 71],
      ["A. Haghighi", "GK", 73],
      ["Mahini", "RB", 73],
      ["Teymourian", "CDM", 75],
      ["Montazeri", "CB", 73],
      ["Ghoochannejhad", "ST", 75],
      ["Alenemeh", "CB", 72],
      ["Rahmani", "CM", 71],
      ["Beikzadeh", "CB", 70],
      ["Beitashour", "RB", 73],
      ["Dejagah", "RW", 76],
      ["Davari", "GK", 71],
      ["Pooladi", "LB", 72],
    ],
    Nigeria: [
      ["Enyeama", "GK", 82],
      ["Yobo", "CB", 76],
      ["Uzoenyi", "LW", 71],
      ["Gabriel", "CM", 72],
      ["Ambrose", "RB", 75],
      ["Egwuekwe", "CB", 73],
      ["Musa", "LW", 80],
      ["Odemwingie", "ST", 76],
      ["Emenike", "ST", 77],
      ["Mikel", "CM", 78],
      ["Moses", "RW", 78],
      ["Odunlami", "LB", 71],
      ["Oshaniwa", "LB", 74],
      ["Oboabona", "CB", 74],
      ["Azeez", "CM", 72],
      ["Ejide", "GK", 71],
      ["Onazi", "CDM", 76],
      ["Babatunde", "RM", 73],
      ["Nwofor", "ST", 71],
      ["Uchebo", "ST", 71],
      ["Agbim", "GK", 70],
      ["Omeruo", "CB", 76],
      ["Ameobi", "ST", 72],
    ],
    Germany: [
      ["Neuer", "GK", 91],
      ["Grosskreutz", "RB", 74],
      ["Ginter", "CB", 73],
      ["Howedes", "LB", 81],
      ["Hummels", "CB", 89],
      ["Khedira", "CM", 83],
      ["Schweinsteiger", "CM", 87],
      ["Ozil", "CAM", 82],
      ["Schurrle", "LW", 82],
      ["Podolski", "LW", 74],
      ["Klose", "ST", 84],
      ["Zieler", "GK", 72],
      ["Muller", "RW", 90],
      ["Draxler", "LW", 74],
      ["Durm", "RB", 73],
      ["Lahm", ["CDM", "RB"], 88],
      ["Mertesacker", "CB", 76],
      ["Kroos", "CM", 92],
      ["Gotze", "CF", 84],
      ["Boateng", "CB", 85],
      ["Mustafi", "CB", 73],
      ["Weidenfeller", "GK", 72],
      ["Kramer", "CM", 74],
    ],
    Portugal: [
      ["Eduardo", "GK", 75],
      ["Bruno Alves", "CB", 75],
      ["Pepe", "CB", 77],
      ["Veloso", "CDM", 75],
      ["Coentrao", "LB", 76],
      ["William Carvalho", "CDM", 76],
      ["Ronaldo", "LW", 86],
      ["Moutinho", "CM", 78],
      ["Almeida", "ST", 73],
      ["Vieirinha", "RM", 73],
      ["Eder", "ST", 73],
      ["Rui Patricio", "GK", 78],
      ["R. Costa", "CB", 73],
      ["Neto", "CB", 73],
      ["Rafa Silva", "CAM", 72],
      ["Meireles", "CM", 76],
      ["Nani", "LW", 79],
      ["Varela", "RW", 73],
      ["Andre Almeida", "RB", 73],
      ["Amorim", "CM", 71],
      ["Joao Pereira", "RB", 74],
      ["Beto", "GK", 71],
      ["Postiga", "ST", 73],
    ],
    Ghana: [
      ["Adams", "GK", 73],
      ["Inkoom", "RB", 72],
      ["Gyan", "ST", 79],
      ["Opare", "RB", 73],
      ["Essien", "CM", 76],
      ["Acquah", "CDM", 74],
      ["Atsu", "LW", 76],
      ["Agyemang-Badu", "CM", 73],
      ["K-P. Boateng", "CAM", 75],
      ["A. Ayew", "LW", 78],
      ["Muntari", "CM", 75],
      ["Kwarasey", "GK", 72],
      ["J. Ayew", "RW", 74],
      ["Adomah", "RW", 74],
      ["Sumaila", "CB", 72],
      ["Dauda", "GK", 71],
      ["Rabiu", "CM", 72],
      ["Waris", "ST", 73],
      ["Mensah", "CB", 74],
      ["Asamoah", "LB", 79],
      ["Boye", "CB", 73],
      ["Wakaso", "LM", 75],
      ["Afful", "RB", 73],
    ],
    USA: [
      ["Howard", "GK", 84],
      ["Yedlin", "RB", 76],
      ["Gonzalez", "CB", 74],
      ["Bradley", "CM", 79],
      ["Besler", "CB", 77],
      ["Brooks", "CB", 76],
      ["Beasley", "LB", 77],
      ["Dempsey", "ST", 82],
      ["Johannsson", "ST", 73],
      ["Diskerud", "CM", 73],
      ["Bedoya", "RM", 75],
      ["Guzan", "GK", 72],
      ["Jones", "CM", 80],
      ["Davis", "LM", 74],
      ["Beckerman", "CDM", 76],
      ["Green", "LW", 73],
      ["Altidore", "ST", 76],
      ["Wondolowski", "ST", 73],
      ["Zusi", "RM", 74],
      ["Cameron", "CB", 76],
      ["Chandler", "RB", 73],
      ["Rimando", "GK", 71],
      ["F. Johnson", "RB", 78],
    ],
    Belgium: [
      ["Courtois", "GK", 84],
      ["Alderweireld", "RB", 80],
      ["Vermaelen", "CB", 75],
      ["Kompany", "CB", 82],
      ["Vertonghen", ["CB", "LB"], 81],
      ["Witsel", "CDM", 80],
      ["De Bruyne", "CAM", 83],
      ["Fellaini", "CM", 79],
      ["Lukaku", "ST", 79],
      ["Hazard", "LW", 84],
      ["Mirallas", "RW", 76],
      ["Mignolet", "GK", 72],
      ["Bossut", "GK", 70],
      ["Mertens", "RW", 78],
      ["Van Buyten", "CB", 76],
      ["Defour", "CM", 74],
      ["Origi", "ST", 77],
      ["Lombaerts", "CB", 74],
      ["Dembele", "CM", 76],
      ["Januzaj", "LW", 74],
      ["Vanden Borre", "RB", 72],
      ["Chadli", "LM", 75],
      ["Ciman", "CB", 72],
    ],
    Algeria: [
      ["Si Mohamed", "GK", 72],
      ["Bougherra", "CB", 77],
      ["Ghoulam", "LB", 75],
      ["Belkalem", "CB", 73],
      ["Halliche", "CB", 75],
      ["Mesbah", "LB", 73],
      ["Yebda", "CDM", 74],
      ["Lacen", "CDM", 75],
      ["Ghilas", "ST", 71],
      ["Feghouli", "RW", 79],
      ["Brahimi", "LW", 78],
      ["Medjani", "CDM", 74],
      ["Slimani", "ST", 78],
      ["Bentaleb", "CM", 76],
      ["Soudani", "ST", 77],
      ["Zemmamouche", "GK", 71],
      ["Cadamuro", "CB", 72],
      ["Djabou", "CAM", 74],
      ["Taider", "CM", 75],
      ["Mandi", "RB", 75],
      ["Mahrez", "RW", 75],
      ["Mostefa", "CDM", 74],
      ["M'Bolhi", "GK", 81],
    ],
    Russia: [
      ["Akinfeev", "GK", 77],
      ["Kozlov", "RB", 73],
      ["Shchennikov", "LB", 73],
      ["Ignashevich", "CB", 77],
      ["Semyonov", "CB", 73],
      ["Kanunnikov", "ST", 71],
      ["Denisov", "CDM", 76],
      ["Glushakov", "CM", 74],
      ["Kokorin", "ST", 75],
      ["Dzagoev", "CAM", 76],
      ["Kerzhakov", "ST", 74],
      ["Lodygin", "GK", 71],
      ["Granat", "CB", 72],
      ["V. Berezutski", "CB", 76],
      ["Mogilevets", "CM", 71],
      ["Ryzhikov", "GK", 71],
      ["Shatov", "LM", 75],
      ["Zhirkov", "LB", 77],
      ["Samedov", "RM", 75],
      ["Fayzulin", "CM", 73],
      ["Ionov", "RW", 73],
      ["Yeshchenko", "RB", 73],
      ["Kombarov", "LB", 75],
    ],
    "South Korea": [
      ["Jung Sung-ryong", "GK", 74],
      ["Kim Chang-soo", "RB", 73],
      ["Yun Suk-young", "LB", 74],
      ["Kwak Tae-hwi", "CB", 73],
      ["Kim Young-gwon", "CB", 75],
      ["Hwang Seok-ho", "CB", 72],
      ["Kim Bo-kyung", "CAM", 74],
      ["Ha Dae-sung", "CM", 72],
      ["Son Heung-min", "LW", 80],
      ["Park Chu-young", "ST", 73],
      ["Lee Keun-ho", "ST", 73],
      ["Lee Yong", "RB", 73],
      ["Koo Ja-cheol", "CAM", 77],
      ["Han Kook-young", "CDM", 73],
      ["Park Jong-woo", "CDM", 73],
      ["Ki Sung-yueng", "CM", 78],
      ["Lee Chung-yong", "RW", 76],
      ["Kim Shin-wook", "ST", 72],
      ["Ji Dong-won", "ST", 74],
      ["Hong Jeong-ho", "CB", 74],
      ["Kim Seung-gyu", "GK", 72],
      ["Park Joo-ho", "LB", 74],
      ["Lee Bum-young", "GK", 70],
    ],
  },
  2018: {
    Russia: [
      ["Akinfeev", "GK", 86],
      ["Mário Fernandes", ["RWB", "RB"], 81],
      ["Kutepov", "CB", 80],
      ["Ignashevich", "CB", 79],
      ["Semyonov", "CB", 74],
      ["Cheryshev", ["LW", "CM"], 84],
      ["Kuzyayev", "CM", 78],
      ["Gazinsky", "CDM", 76],
      ["Dzagoev", "CAM", 74],
      ["Smolov", "ST", 73],
      ["Zobnin", "CM", 80],
      ["Lunyov", "GK", 71],
      ["Kudryashov", ["CB", "LB"], 79],
      ["Granat", "CB", 73],
      ["Aleksei Miranchuk", "CAM", 74],
      ["Anton Miranchuk", "CM", 71],
      ["Golovin", ["CAM", "CM"], 83],
      ["Zhirkov", "LWB", 80],
      ["Samedov", "RM", 75],
      ["Gabulov", "GK", 71],
      ["Yerokhin", "CM", 72],
      ["Dzyuba", "ST", 82],
      ["Smolnikov", "RB", 74],
    ],
    "Saudi Arabia": [
      ["Al-Mayouf", "GK", 72],
      ["Al-Harbi", "LB", 72],
      ["Osama Hawsawi", "CB", 74],
      ["Al-Bulaihi", "CB", 73],
      ["Omar Hawsawi", "CB", 72],
      ["Al-Breik", "RB", 73],
      ["Al-Faraj", ["CM", "CAM"], 76],
      ["Al-Shehri", "RM", 73],
      ["Bahebri", "CAM", 71],
      ["Al-Sahlawi", "ST", 72],
      ["Al-Khaibri", "CM", 71],
      ["Kanno", "CM", 71],
      ["Al-Shahrani", "LB", 74],
      ["Otayf", "CDM", 73],
      ["Abdullah Al-Khaibari", "CM", 70],
      ["Al-Mogahwi", "CM", 72],
      ["Al-Jassim", "CM", 73],
      ["Al-Dawsari", ["LW", "LM"], 76],
      ["Al-Muwallad", ["RW", "ST"], 74],
      ["Assiri", "ST", 70],
      ["Al-Mosailem", "GK", 71],
      ["Al-Owais", "GK", 71],
      ["Motaz Hawsawi", "CB", 71],
    ],
    Egypt: [
      ["El Hadary", "GK", 76],
      ["Gabr", "CB", 72],
      ["Elmohamady", "RB", 75],
      ["Gaber", ["RB", "CM"], 73],
      ["Morsy", "CM", 71],
      ["Hegazi", "CB", 77],
      ["Fathy", ["RB", "CB"], 74],
      ["Hamed", "CDM", 74],
      ["Marwan Mohsen", "ST", 72],
      ["Salah", ["LW", "RW"], 85],
      ["Kahraba", "ST", 71],
      ["Ayman Ashraf", "LB", 71],
      ["Abdel Shafy", "LB", 73],
      ["Ramadan Sobhi", "LW", 72],
      ["Mahmoud Hamdy", "CB", 70],
      ["Ekramy", "GK", 71],
      ["Elneny", "CM", 76],
      ["Shikabala", "RW", 71],
      ["El Said", "CAM", 73],
      ["Saad Samir", "CB", 70],
      ["Trézéguet", ["LW", "RW"], 74],
      ["Amr Warda", "RW", 71],
      ["El Shenawy", "GK", 73],
    ],
    Uruguay: [
      ["Muslera", "GK", 83],
      ["Giménez", "CB", 84],
      ["Godín", "CB", 87],
      ["Varela", "RB", 71],
      ["C. Sánchez", "CDM", 76],
      ["Bentancur", "CM", 80],
      ["C. Rodríguez", "LM", 73],
      ["Nández", ["RM", "CM"], 78],
      ["Suárez", "ST", 85],
      ["De Arrascaeta", "CAM", 73],
      ["Stuani", ["ST", "CF"], 72],
      ["Campaña", "GK", 71],
      ["Gastón Silva", "LB", 71],
      ["Torreira", "CDM", 81],
      ["Vecino", "CM", 80],
      ["Maxi Pereira", "RB", 76],
      ["Laxalt", ["LB", "LM"], 79],
      ["Maxi Gómez", "ST", 72],
      ["Coates", "CB", 75],
      ["Urretaviscaya", "RW", 71],
      ["Cavani", "ST", 86],
      ["Cáceres", ["RB", "CB"], 78],
      ["Martín Silva", "GK", 71],
    ],
    Portugal: [
      ["Rui Patrício", "GK", 84],
      ["Anthony Lopes", "GK", 76],
      ["Beto", "GK", 72],
      ["Pepe", "CB", 84],
      ["José Fonte", "CB", 78],
      ["Bruno Alves", "CB", 76],
      ["Rúben Dias", "CB", 74],
      ["Cédric Soares", "RB", 78],
      ["Ricardo Pereira", "RB", 77],
      ["Raphaël Guerreiro", ["LB", "LM"], 80],
      ["Mário Rui", "LB", 75],
      ["William Carvalho", "CDM", 80],
      ["João Moutinho", "CM", 81],
      ["Bruno Fernandes", ["CM", "CAM"], 77],
      ["João Mário", ["LM", "CM"], 77],
      ["Adrien Silva", "CM", 75],
      ["Manuel Fernandes", "CM", 73],
      ["Bernardo Silva", ["RW", "RM"], 82],
      ["Cristiano Ronaldo", "ST", 91],
      ["Gonçalo Guedes", ["LW", "ST"], 76],
      ["Gelson Martins", "RW", 75],
      ["Ricardo Quaresma", "RW", 77],
      ["André Silva", "ST", 75],
    ],
    Spain: [
      ["De Gea", "GK", 83],
      ["Reina", "GK", 76],
      ["Kepa", "GK", 74],
      ["Ramos", "CB", 86],
      ["Piqué", "CB", 84],
      ["Nacho", ["CB", "RB"], 78],
      ["Azpilicueta", ["CB", "RB"], 78],
      ["Carvajal", "RB", 81],
      ["Odriozola", "RB", 74],
      ["Jordi Alba", "LB", 82],
      ["Monreal", "LB", 76],
      ["Busquets", "CDM", 84],
      ["Iniesta", ["CM", "CAM"], 84],
      ["Isco", "CAM", 85],
      ["David Silva", "CM", 82],
      ["Thiago", "CM", 80],
      ["Koke", "CM", 79],
      ["Saúl", "CM", 78],
      ["Asensio", ["LW", "RW"], 79],
      ["Lucas Vázquez", "RW", 77],
      ["Diego Costa", "ST", 82],
      ["Iago Aspas", ["ST", "CF"], 78],
      ["Rodrigo", "ST", 76],
    ],
    Morocco: [
      ["El Kajoui", "GK", 73],
      ["Bounou", "GK", 74],
      ["Tagnaouti", "GK", 71],
      ["Benatia", "CB", 80],
      ["Saïss", "CB", 77],
      ["Da Costa", "CB", 73],
      ["Hakimi", "RB", 77],
      ["Dirar", ["RB", "RM"], 74],
      ["Mendyl", "LB", 72],
      ["El Ahmadi", "CDM", 75],
      ["Boussoufa", "CAM", 74],
      ["Belhanda", "CAM", 75],
      ["S. Amrabat", "CM", 73],
      ["Fajr", "CM", 73],
      ["Aït Bennasser", "CM", 72],
      ["Harit", ["CAM", "LW"], 73],
      ["Ziyech", ["CAM", "RW"], 78],
      ["N. Amrabat", ["RW", "RM"], 75],
      ["Carcela", ["RW", "CAM"], 73],
      ["Boutaïb", "ST", 73],
      ["En-Nesyri", "ST", 73],
      ["El Kaabi", "ST", 72],
      ["Bouhaddouz", "ST", 71],
    ],
    Iran: [
      ["Beyranvand", "GK", 80],
      ["Mazaheri", "GK", 71],
      ["Abedzadeh", "GK", 71],
      ["Pouraliganji", "CB", 73],
      ["Majid Hosseini", "CB", 73],
      ["Montazeri", "CB", 72],
      ["Khanzadeh", "CB", 71],
      ["Cheshmi", ["CDM", "CB"], 72],
      ["Hajsafi", "LB", 74],
      ["Mohammadi", "LB", 72],
      ["Rezaeian", "RB", 72],
      ["Ezatollahi", "CDM", 74],
      ["Shojaei", "CM", 73],
      ["Ebrahimi", "CM", 73],
      ["Torabi", ["RM", "CAM"], 72],
      ["Amiri", ["LM", "LW"], 73],
      ["Jahanbakhsh", ["RW", "LW"], 76],
      ["Azmoun", "ST", 77],
      ["Taremi", "ST", 76],
      ["Ansarifard", "ST", 73],
      ["Ghoddos", ["CAM", "CF"], 73],
      ["Ghoochannejhad", "ST", 73],
      ["Dejagah", ["CAM", "CM"], 72],
    ],
    France: [
      ["Lloris", "GK", 82],
      ["Mandanda", "GK", 74],
      ["Areola", "GK", 72],
      ["Varane", "CB", 84],
      ["Umtiti", "CB", 83],
      ["Pavard", "RB", 81],
      ["Lucas Hernández", "LB", 80],
      ["Mendy", "LB", 76],
      ["Kimpembe", "CB", 75],
      ["Sidibé", "RB", 74],
      ["Rami", "CB", 73],
      ["Kanté", "CDM", 85],
      ["Pogba", "CM", 85],
      ["Matuidi", ["CM", "LM"], 78],
      ["Tolisso", "CM", 76],
      ["N'Zonzi", "CDM", 75],
      ["Mbappé", ["RW", "ST"], 88],
      ["Griezmann", ["CF", "ST"], 87],
      ["Giroud", "ST", 79],
      ["Dembélé", "RW", 77],
      ["Fekir", "CAM", 76],
      ["Lemar", "LM", 75],
      ["Thauvin", "RW", 73],
    ],
    Australia: [
      ["Ryan", "GK", 76],
      ["Jones", "GK", 71],
      ["Vukovic", "GK", 70],
      ["Sainsbury", "CB", 74],
      ["Milligan", ["CB", "CDM"], 73],
      ["Behich", "LB", 73],
      ["Degenek", "CB", 72],
      ["Risdon", "RB", 72],
      ["Meredith", "LB", 71],
      ["Jurman", "CB", 70],
      ["Mooy", "CM", 76],
      ["Jedinak", "CDM", 75],
      ["Rogic", "CAM", 74],
      ["Leckie", ["RM", "RW"], 74],
      ["Irvine", "CM", 72],
      ["Luongo", "CM", 71],
      ["Kruse", "LW", 72],
      ["Cahill", "ST", 73],
      ["Nabbout", "ST", 72],
      ["Arzani", "LW", 72],
      ["Juric", "ST", 71],
      ["Maclaren", "ST", 70],
      ["Petratos", "LM", 70],
    ],
    Peru: [
      ["Gallese", "GK", 74],
      ["Cáceda", "GK", 71],
      ["Carvallo", "GK", 70],
      ["Advíncula", "RB", 73],
      ["Trauco", "LB", 73],
      ["Santamaría", "CB", 73],
      ["Ramos", "CB", 72],
      ["A. Rodríguez", "CB", 72],
      ["Corzo", "RB", 71],
      ["Araujo", "CB", 71],
      ["Loyola", "LB", 70],
      ["Guerrero", "ST", 76],
      ["Carrillo", ["RW", "RM"], 76],
      ["Cueva", "CAM", 75],
      ["Farfán", ["ST", "RW"], 75],
      ["Tapia", "CDM", 74],
      ["Yotún", "CM", 74],
      ["Flores", "LW", 73],
      ["Aquino", "CDM", 72],
      ["Ruidíaz", "ST", 72],
      ["Hurtado", "CM", 71],
      ["Polo", "RM", 71],
      ["Cartagena", "CM", 70],
    ],
    Denmark: [
      ["Schmeichel", "GK", 82],
      ["Lössl", "GK", 73],
      ["Rønnow", "GK", 71],
      ["Kjær", "CB", 78],
      ["Christensen", "CB", 76],
      ["Stryger Larsen", "RB", 74],
      ["Vestergaard", "CB", 74],
      ["M. Jørgensen", "CB", 74],
      ["Dalsgaard", "RB", 73],
      ["Knudsen", "LB", 73],
      ["Eriksen", ["CAM", "CM"], 83],
      ["Delaney", "CM", 76],
      ["Schöne", "CM", 74],
      ["Kvist", "CDM", 73],
      ["Lerager", "CM", 72],
      ["Krohn-Dehli", "LM", 72],
      ["Poulsen", ["RW", "ST"], 75],
      ["N. Jørgensen", "ST", 73],
      ["Braithwaite", "ST", 73],
      ["Dolberg", "ST", 73],
      ["Sisto", ["LW", "RW"], 73],
      ["Fischer", "LW", 72],
      ["Cornelius", "ST", 72],
    ],
    Argentina: [
      ["Caballero", "GK", 76],
      ["Armani", "GK", 77],
      ["Guzmán", "GK", 73],
      ["Mercado", ["RB", "CB"], 78],
      ["Otamendi", "CB", 84],
      ["Fazio", "CB", 78],
      ["Rojo", ["CB", "LB"], 78],
      ["Tagliafico", "LB", 79],
      ["Acuña", ["LB", "LM"], 77],
      ["Ansaldi", ["RB", "LB"], 76],
      ["Salvio", ["RM", "RB"], 77],
      ["Mascherano", "CDM", 82],
      ["Banega", "CM", 82],
      ["Biglia", "CDM", 79],
      ["Lo Celso", "CM", 78],
      ["Di María", ["LW", "RW"], 84],
      ["Meza", ["CAM", "RM"], 77],
      ["Enzo Pérez", "CM", 77],
      ["Messi", ["RW", "CF"], 90],
      ["Agüero", "ST", 86],
      ["Higuaín", "ST", 82],
      ["Dybala", ["CF", "CAM"], 84],
      ["Pavón", ["RW", "LW"], 78],
    ],
    Croatia: [
      ["Subašić", "GK", 81],
      ["Kalinić", "GK", 74],
      ["Livaković", "GK", 73],
      ["Vrsaljko", "RB", 80],
      ["Ćorluka", "CB", 77],
      ["Vida", "CB", 80],
      ["Lovren", "CB", 81],
      ["Strinić", "LB", 76],
      ["Pivarić", "LB", 74],
      ["Jedvaj", ["RB", "CB"], 75],
      ["Ćaleta-Car", "CB", 74],
      ["Modrić", "CM", 89],
      ["Rakitić", "CM", 85],
      ["Kovačić", "CM", 81],
      ["Brozović", ["CDM", "CM"], 80],
      ["Badelj", "CDM", 77],
      ["Bradarić", "CM", 73],
      ["Perišić", ["LM", "LW"], 84],
      ["Rebić", ["RW", "ST"], 78],
      ["Kramarić", ["CF", "ST"], 79],
      ["Pjaca", "LW", 75],
      ["Mandžukić", "ST", 84],
      ["Nikola Kalinić", "ST", 77],
    ],
    Iceland: [
      ["Halldórsson", "GK", 76],
      ["Schram", "GK", 70],
      ["Rúnarsson", "GK", 71],
      ["Sævarsson", "RB", 73],
      ["Magnússon", ["LB", "CB"], 73],
      ["Ragnar Sigurðsson", "CB", 76],
      ["Árnason", "CB", 75],
      ["Ingason", "CB", 74],
      ["Ari Skúlason", "LB", 72],
      ["Eyjólfsson", "CB", 71],
      ["Hallfreðsson", ["CDM", "CM"], 73],
      ["Bjarnason", "CM", 75],
      ["Gunnarsson", "CDM", 75],
      ["Ólafur Skúlason", "CM", 72],
      ["Gylfi Sigurðsson", "CAM", 82],
      ["Traustason", ["LM", "CM"], 71],
      ["Gíslason", "RM", 72],
      ["Friðjónsson", "CM", 70],
      ["Jóhann Berg Guðmundsson", ["RM", "LM"], 77],
      ["Finnbogason", "ST", 75],
      ["Böðvarsson", ["ST", "LW"], 73],
      ["Sigurðarson", "ST", 72],
      ["Albert Guðmundsson", ["ST", "LW"], 71],
    ],
    Nigeria: [
      ["Uzoho", "GK", 71],
      ["Ezenwa", "GK", 71],
      ["Akpeyi", "GK", 71],
      ["Troost-Ekong", "CB", 74],
      ["Balogun", "CB", 75],
      ["Omeruo", "CB", 74],
      ["Awaziem", ["CB", "RB"], 72],
      ["Shehu", "RB", 72],
      ["Idowu", "LB", 72],
      ["Echiéjilé", "LB", 73],
      ["Ebuehi", "RB", 72],
      ["Mikel", ["CM", "CAM"], 79],
      ["Ndidi", "CDM", 78],
      ["Etebo", "CM", 75],
      ["Ogu", "CM", 72],
      ["Joel Obi", ["CM", "LM"], 73],
      ["Onazi", "CDM", 73],
      ["Musa", ["RW", "LW"], 76],
      ["Moses", ["RW", "RM"], 78],
      ["Iwobi", ["CAM", "LW"], 76],
      ["Iheanacho", "ST", 76],
      ["Ighalo", "ST", 74],
      ["Nwankwo", "ST", 71],
    ],
    Brazil: [
      ["Alisson", "GK", 85],
      ["Ederson", "GK", 82],
      ["Cássio", "GK", 74],
      ["Danilo", "RB", 79],
      ["Fágner", "RB", 76],
      ["Marcelo", "LB", 83],
      ["Filipe Luís", "LB", 80],
      ["Thiago Silva", "CB", 84],
      ["Miranda", "CB", 81],
      ["Marquinhos", "CB", 82],
      ["Pedro Geromel", "CB", 75],
      ["Casemiro", "CDM", 84],
      ["Fernandinho", "CDM", 81],
      ["Paulinho", "CM", 79],
      ["Fred", "CM", 76],
      ["Renato Augusto", "CM", 78],
      ["Coutinho", ["CAM", "LW"], 84],
      ["Willian", "RW", 80],
      ["Douglas Costa", ["RW", "LW"], 79],
      ["Neymar", "LW", 88],
      ["Gabriel Jesus", "ST", 80],
      ["Roberto Firmino", "ST", 79],
      ["Taison", "LW", 76],
    ],
    Switzerland: [
      ["Sommer", "GK", 80],
      ["Bürki", "GK", 76],
      ["Mvogo", "GK", 73],
      ["Lichtsteiner", "RB", 77],
      ["Ricardo Rodríguez", "LB", 79],
      ["Akanji", "CB", 78],
      ["Schär", "CB", 77],
      ["Elvedi", "CB", 75],
      ["Djourou", "CB", 74],
      ["Lang", "RB", 74],
      ["Moubandje", "LB", 72],
      ["Behrami", "CDM", 76],
      ["Xhaka", "CM", 81],
      ["Zakaria", ["CDM", "CM"], 76],
      ["Freuler", "CM", 76],
      ["Gelson Fernandes", "CDM", 74],
      ["Džemaili", "CM", 75],
      ["Zuber", "LM", 76],
      ["Shaqiri", ["RW", "CAM"], 82],
      ["Seferović", "ST", 75],
      ["Embolo", "ST", 75],
      ["Drmić", "ST", 74],
      ["Gavranović", "ST", 73],
    ],
    "Costa Rica": [
      ["Navas", "GK", 83],
      ["Pemberton", "GK", 72],
      ["Moreira", "GK", 71],
      ["Gamboa", "RB", 73],
      ["Ian Smith", "RB", 71],
      ["Matarrita", "LB", 73],
      ["Oviedo", "LB", 74],
      ["Duarte", "CB", 74],
      ["González", "CB", 74],
      ["Calvo", ["CB", "LB"], 73],
      ["Waston", "CB", 74],
      ["Acosta", "CB", 72],
      ["Guzmán", "CDM", 73],
      ["Tejeda", "CM", 73],
      ["Borges", "CM", 75],
      ["Azofeifa", "CM", 72],
      ["Bolaños", ["RM", "RW"], 73],
      ["Colindres", ["LW", "CAM"], 72],
      ["Wallace", ["LM", "LW"], 73],
      ["Bryan Ruiz", ["CAM", "CF"], 77],
      ["Campbell", ["RW", "ST"], 75],
      ["Ureña", "ST", 73],
      ["Venegas", "ST", 72],
    ],
    Serbia: [
      ["Stojković", "GK", 75],
      ["Rajković", "GK", 73],
      ["Dmitrović", "GK", 72],
      ["Rukavina", "RB", 73],
      ["Tošić", "CB", 74],
      ["Spajić", "CB", 72],
      ["Ivanović", ["CB", "RB"], 78],
      ["Kolarov", ["LB", "LWB"], 79],
      ["Veljković", "CB", 73],
      ["Milenković", "CB", 75],
      ["Matić", "CDM", 80],
      ["Milivojević", "CDM", 77],
      ["Grujić", "CM", 74],
      ["Tadić", ["CAM", "LW"], 79],
      ["Živković", ["RM", "RW"], 74],
      ["Kostić", ["LM", "LWB"], 76],
      ["Ljajić", ["CAM", "LW"], 76],
      ["Radonjić", ["RW", "LW"], 73],
      ["Milinković-Savić", "CM", 80],
      ["Gaćinović", ["CAM", "RW"], 73],
      ["Prijović", "ST", 73],
      ["Jović", "ST", 75],
      ["Mitrović", "ST", 78],
    ],
    Germany: [
      ["Neuer", "GK", 88],
      ["ter Stegen", "GK", 87],
      ["Trapp", "GK", 78],
      ["Hummels", "CB", 86],
      ["Boateng", "CB", 84],
      ["Kimmich", "RB", 84],
      ["Rüdiger", "CB", 81],
      ["Süle", "CB", 81],
      ["Hector", "LB", 80],
      ["Ginter", "CB", 79],
      ["Plattenhardt", "LB", 76],
      ["Kroos", "CM", 88],
      ["Özil", "CAM", 85],
      ["Gündoğan", "CM", 83],
      ["Khedira", "CDM", 82],
      ["Draxler", ["LM", "CAM"], 82],
      ["Goretzka", "CM", 81],
      ["Rudy", "CDM", 78],
      ["Müller", ["RW", "CF"], 85],
      ["Reus", ["LW", "CAM"], 84],
      ["Werner", "ST", 82],
      ["Brandt", ["LW", "RW"], 80],
      ["Mario Gómez", "ST", 79],
    ],
    Mexico: [
      ["Ochoa", "GK", 83],
      ["Talavera", "GK", 76],
      ["José de Jesús Corona", "GK", 75],
      ["Héctor Moreno", "CB", 79],
      ["Layún", ["RB", "LB"], 79],
      ["Rafael Márquez", "CB", 77],
      ["Salcedo", "CB", 77],
      ["Edson Álvarez", ["CB", "RB"], 76],
      ["Diego Reyes", "CB", 76],
      ["Gallardo", "LB", 76],
      ["Ayala", "CB", 75],
      ["Guardado", "CM", 81],
      ["Héctor Herrera", "CM", 81],
      ["Giovani dos Santos", "CAM", 78],
      ["Jonathan dos Santos", "CM", 78],
      ["Fabián", "CAM", 77],
      ["Aquino", ["LM", "RM"], 75],
      ["Javier Hernández", "ST", 82],
      ["Lozano", "LW", 81],
      ["Jesús Manuel Corona", "RW", 80],
      ["Vela", ["RW", "ST"], 80],
      ["Raúl Jiménez", "ST", 78],
      ["Peralta", "ST", 76],
    ],
    Sweden: [
      ["Robin Olsen", "GK", 80],
      ["Johnsson", "GK", 74],
      ["Nordfeldt", "GK", 73],
      ["Granqvist", "CB", 81],
      ["Lindelöf", "CB", 80],
      ["Lustig", "RB", 78],
      ["Augustinsson", "LB", 78],
      ["Martin Olsson", "LB", 76],
      ["Jansson", "CB", 76],
      ["Helander", "CB", 74],
      ["Krafth", "RB", 73],
      ["Forsberg", ["LW", "CAM"], 82],
      ["Ekdal", "CM", 78],
      ["Claesson", ["RM", "RW"], 77],
      ["Sebastian Larsson", ["CM", "RM"], 76],
      ["Gustav Svensson", "CDM", 75],
      ["Hiljemark", "CM", 74],
      ["Durmaz", "RM", 74],
      ["Rohdén", "CM", 73],
      ["Toivonen", ["ST", "CF"], 77],
      ["Berg", "ST", 77],
      ["Guidetti", "ST", 75],
      ["Kiese Thelin", "ST", 73],
    ],
    "South Korea": [
      ["Jo Hyeon-woo", "GK", 77],
      ["Kim Seung-gyu", "GK", 74],
      ["Kim Jin-hyeon", "GK", 73],
      ["Kim Young-gwon", "CB", 76],
      ["Jang Hyun-soo", "CB", 73],
      ["Lee Yong", "RB", 73],
      ["Go Yo-han", ["RB", "RM"], 73],
      ["Kim Min-woo", "LB", 73],
      ["Park Joo-ho", "LB", 73],
      ["Hong Chul", "LB", 73],
      ["Yun Yong-sun", "CB", 72],
      ["Oh Ban-suk", "CB", 72],
      ["Jung Seung-hyun", "CB", 71],
      ["Ki Sung-yueng", "CM", 78],
      ["Koo Ja-cheol", ["CM", "CAM"], 75],
      ["Lee Jae-sung", ["CAM", "CM"], 75],
      ["Jung Woo-young", "CDM", 74],
      ["Ju Se-jong", "CM", 73],
      ["Son Heung-min", ["LW", "ST"], 84],
      ["Hwang Hee-chan", "ST", 74],
      ["Lee Seung-woo", ["LW", "CF"], 72],
      ["Moon Seon-min", ["RW", "RM"], 72],
      ["Kim Shin-wook", "ST", 72],
    ],
    Belgium: [
      ["Courtois", "GK", 87],
      ["Mignolet", "GK", 78],
      ["Casteels", "GK", 74],
      ["Alderweireld", "CB", 84],
      ["Vertonghen", "CB", 83],
      ["Kompany", "CB", 82],
      ["Boyata", "CB", 76],
      ["Vermaelen", "CB", 77],
      ["Meunier", ["RWB", "RB"], 80],
      ["Carrasco", ["LWB", "LM"], 78],
      ["Witsel", "CDM", 81],
      ["De Bruyne", "CM", 88],
      ["Tielemans", "CM", 76],
      ["Dembélé", "CM", 78],
      ["Dendoncker", "CDM", 74],
      ["Fellaini", ["CM", "CDM"], 78],
      ["Januzaj", ["RW", "LW"], 75],
      ["E. Hazard", ["LW", "CAM"], 88],
      ["Mertens", ["RW", "ST"], 80],
      ["Lukaku", "ST", 84],
      ["Batshuayi", "ST", 76],
      ["Chadli", ["LM", "LWB"], 76],
      ["T. Hazard", ["LW", "LM"], 75],
    ],
    England: [
      ["Pickford", "GK", 82],
      ["Butland", "GK", 76],
      ["Pope", "GK", 73],
      ["Walker", ["CB", "RB"], 82],
      ["Stones", "CB", 81],
      ["Maguire", "CB", 80],
      ["Cahill", "CB", 77],
      ["Jones", "CB", 76],
      ["Trippier", ["RWB", "RM"], 80],
      ["Young", ["LWB", "LB"], 78],
      ["Rose", ["LWB", "LB"], 76],
      ["Alexander-Arnold", "RB", 76],
      ["Delph", ["LB", "CM"], 75],
      ["Henderson", "CDM", 80],
      ["Dier", ["CDM", "CM"], 77],
      ["Alli", ["CAM", "CM"], 80],
      ["Lingard", ["CAM", "RM"], 78],
      ["Loftus-Cheek", ["CM", "CAM"], 76],
      ["Kane", "ST", 85],
      ["Sterling", ["RW", "ST"], 81],
      ["Rashford", ["ST", "LW"], 78],
      ["Vardy", "ST", 77],
      ["Welbeck", "ST", 75],
    ],
    Tunisia: [
      ["Hassen", "GK", 72],
      ["Ben Mustapha", "GK", 72],
      ["Mathlouthi", "GK", 71],
      ["Benalouane", "CB", 73],
      ["S. Ben Youssef", "CB", 73],
      ["Bedoui", ["CB", "RB"], 71],
      ["Bronn", "CB", 73],
      ["Haddadi", "LB", 72],
      ["Maâloul", "LB", 74],
      ["Meriah", "CB", 72],
      ["Nagguez", "RB", 71],
      ["Badri", ["LW", "CAM"], 73],
      ["Ben Amor", "CDM", 72],
      ["Chaaleli", "CM", 71],
      ["Khaoui", ["CM", "RM"], 72],
      ["Sassi", ["CM", "CDM"], 74],
      ["Skhiri", ["CDM", "CM"], 75],
      ["Sliti", ["LW", "CAM"], 74],
      ["Srarfi", ["RW", "RM"], 72],
      ["F. Ben Youssef", "ST", 72],
      ["Khalifa", "ST", 71],
      ["Khazri", ["ST", "CF"], 76],
      ["Khenissi", "ST", 71],
    ],
    Panama: [
      ["Penedo", "GK", 73],
      ["Calderón", "GK", 71],
      ["Alex Rodríguez", "GK", 70],
      ["Baloy", "CB", 72],
      ["Cummings", "CB", 71],
      ["Davis", ["LB", "LWB"], 72],
      ["Escobar", "CB", 71],
      ["Machado", "CB", 72],
      ["Murillo", "RB", 72],
      ["Ovalle", "LB", 70],
      ["R. Torres", "CB", 73],
      ["Bárcenas", ["LW", "LM"], 71],
      ["Cooper", ["CM", "RM"], 72],
      ["Godoy", "CDM", 73],
      ["Gómez", ["CDM", "CM"], 71],
      ["Pimentel", "CM", 70],
      ["Quintero", ["RM", "RW"], 71],
      ["José Luis Rodríguez", ["LW", "RW"], 71],
      ["Arroyo", "ST", 70],
      ["Díaz", ["ST", "CF"], 71],
      ["Blas Pérez", "ST", 72],
      ["Tejada", "ST", 72],
      ["G. Torres", "ST", 71],
    ],
    Poland: [
      ["Szczęsny", "GK", 82],
      ["Fabiański", "GK", 78],
      ["Białkowski", "GK", 72],
      ["Piszczek", "RB", 79],
      ["Bereszyński", "RB", 75],
      ["Glik", "CB", 78],
      ["Pazdan", "CB", 73],
      ["Bednarek", "CB", 74],
      ["Cionek", "CB", 72],
      ["Jędrzejczyk", ["LB", "CB"], 73],
      ["Rybus", "LB", 74],
      ["Krychowiak", "CDM", 79],
      ["Zieliński", ["CM", "CAM"], 80],
      ["Linetty", "CM", 74],
      ["Góralski", "CDM", 72],
      ["Kurzawa", "CM", 71],
      ["Błaszczykowski", ["RM", "RW"], 76],
      ["Grosicki", ["LM", "LW"], 76],
      ["Peszko", "RM", 72],
      ["Lewandowski", "ST", 85],
      ["Milik", "ST", 76],
      ["Teodorczyk", "ST", 73],
      ["Kownacki", "ST", 72],
    ],
    Senegal: [
      ["Khadim N'Diaye", "GK", 72],
      ["Diallo", "GK", 73],
      ["Gomis", "GK", 72],
      ["Gassama", "RB", 73],
      ["Wagué", "RB", 73],
      ["Sabaly", ["LB", "RB"], 74],
      ["Ciss", "LB", 72],
      ["Koulibaly", "CB", 83],
      ["Sané", "CB", 77],
      ["Mbodji", "CB", 76],
      ["Kouyaté", ["CDM", "CB"], 76],
      ["Gana Gueye", ["CDM", "CM"], 79],
      ["Badou Ndiaye", "CM", 75],
      ["Alfred N'Diaye", "CM", 73],
      ["N'Doye", "CM", 72],
      ["Mané", "LW", 85],
      ["Keita Baldé", ["LW", "ST"], 76],
      ["Niang", ["ST", "RW"], 74],
      ["Sarr", "RW", 74],
      ["Diouf", "ST", 73],
      ["Konaté", "ST", 73],
      ["Sakho", "ST", 72],
      ["Sow", "ST", 72],
    ],
    Colombia: [
      ["Ospina", "GK", 80],
      ["Vargas", "GK", 72],
      ["J.F. Cuadrado", "GK", 71],
      ["Arias", "RB", 78],
      ["Davinson Sánchez", "CB", 79],
      ["Yerry Mina", "CB", 78],
      ["Zapata", "CB", 76],
      ["Murillo", "CB", 74],
      ["Fabra", "LB", 74],
      ["Mojica", "LB", 73],
      ["Barrios", "CDM", 76],
      ["C. Sánchez", "CDM", 74],
      ["Lerma", ["CDM", "CM"], 75],
      ["Uribe", "CM", 75],
      ["Aguilar", "CM", 73],
      ["James Rodríguez", "CAM", 84],
      ["Quintero", "CAM", 77],
      ["Cuadrado", ["RM", "RW"], 80],
      ["Izquierdo", "LW", 75],
      ["Falcao", "ST", 82],
      ["Bacca", "ST", 76],
      ["Muriel", ["ST", "LW"], 76],
      ["Borja", "ST", 73],
    ],
    Japan: [
      ["Kawashima", "GK", 75],
      ["Higashiguchi", "GK", 73],
      ["Nakamura", "GK", 72],
      ["Hiroki Sakai", "RB", 76],
      ["Yoshida", "CB", 78],
      ["Shoji", "CB", 74],
      ["Makino", "CB", 72],
      ["Ueda", "CB", 71],
      ["Nagatomo", "LB", 75],
      ["Gotoku Sakai", "LB", 73],
      ["Hasebe", ["CDM", "CB"], 77],
      ["Endo", ["CDM", "CB"], 72],
      ["Shibasaki", "CM", 76],
      ["Yamaguchi", "CM", 73],
      ["Oshima", "CM", 72],
      ["Kagawa", "CAM", 78],
      ["Honda", ["CAM", "RW"], 78],
      ["Inui", "LW", 76],
      ["Haraguchi", ["LM", "RM"], 74],
      ["Usami", "LW", 72],
      ["Osako", "ST", 76],
      ["Okazaki", "ST", 76],
      ["Muto", "ST", 73],
    ],
  },
  2022: {
    Argentina: [
      ["E. Martínez", "GK", 87],
      ["Molina", "RB", 80],
      ["C. Romero", "CB", 84],
      ["Otamendi", "CB", 82],
      ["Tagliafico", "LB", 80],
      ["De Paul", "CM", 84],
      ["E. Fernández", "CM", 84],
      ["Mac Allister", "CM", 84],
      ["Di María", ["LW", "RW"], 86],
      ["Messi", "CF", 95],
      ["J. Álvarez", "ST", 84],
    ],
    France: [
      ["Lloris", "GK", 85],
      ["Pavard", "RB", 83],
      ["Varane", "CB", 85],
      ["Upamecano", "CB", 82],
      ["T. Hernández", "LB", 84],
      ["Tchouaméni", "CDM", 84],
      ["Camavinga", "CM", 82],
      ["Griezmann", ["CAM", "LW"], 88],
      ["Dembélé", ["RW", "LW"], 83],
      ["Mbappé", ["LW", "ST"], 93],
      ["Giroud", "ST", 82],
    ],
    Croatia: [
      ["Livaković", "GK", 83],
      ["Juranović", "RB", 80],
      ["Lovren", "CB", 80],
      ["Gvardiol", "LB", 84],
      ["Sosa", "LWB", 79],
      ["Brozović", "CDM", 84],
      ["Modrić", ["CAM", "CM"], 88],
      ["Kovačić", "CM", 83],
      ["Vlašić", "RM", 79],
      ["Kramarić", "CF", 81],
      ["Perišić", "LW", 84],
    ],
    Morocco: [
      ["Bono", "GK", 85],
      ["Hakimi", "RB", 85],
      ["Saïss", "CB", 80],
      ["Aguerd", "CB", 80],
      ["Mazraoui", "LB", 81],
      ["Amrabat", "CDM", 85],
      ["Ounahi", "CM", 80],
      ["Amallah", "CM", 78],
      ["Ziyech", "RW", 83],
      ["Boufal", "LW", 80],
      ["En-Nesyri", "ST", 81],
    ],
    Brazil: [
      ["Alisson", "GK", 89],
      ["Militão", "RB", 83],
      ["Marquinhos", "CB", 86],
      ["Thiago Silva", "CB", 84],
      ["Alex Sandro", "LB", 81],
      ["Casemiro", "CDM", 87],
      ["Paquetá", "CAM", 82],
      ["Raphinha", "RW", 82],
      ["Neymar", ["CF", "LW"], 89],
      ["Vinícius", "LW", 86],
      ["Richarlison", "ST", 82],
    ],
    Portugal: [
      ["D. Costa", "GK", 80],
      ["Cancelo", "RB", 86],
      ["Pepe", "CB", 82],
      ["Rúben Dias", "CB", 87],
      ["Guerreiro", "LB", 82],
      ["Danilo", "CDM", 80],
      ["Vitinha", "CM", 82],
      ["B. Fernandes", "CAM", 86],
      ["R. Leão", "LW", 83],
      ["Ronaldo", "CF", 87],
      ["G. Ramos", "ST", 80],
    ],
    Netherlands: [
      ["Noppert", "GK", 79],
      ["Dumfries", "RB", 82],
      ["van Dijk", "CB", 89],
      ["de Ligt", "CB", 83],
      ["Blind", "LB", 80],
      ["F. de Jong", "CDM", 87],
      ["Koopmeiners", "CM", 82],
      ["Berghuis", "CAM", 80],
      ["Bergwijn", "RW", 80],
      ["Depay", "ST", 84],
      ["Gakpo", ["LW", "ST"], 84],
    ],
    England: [
      ["Pickford", "GK", 83],
      ["Walker", "RB", 83],
      ["Stones", "CB", 84],
      ["Maguire", "CB", 80],
      ["Shaw", "LB", 82],
      ["Rice", "CDM", 84],
      ["Bellingham", ["CM", "CAM"], 86],
      ["Mount", "CAM", 82],
      ["Saka", "RW", 85],
      ["Kane", "ST", 89],
      ["Foden", ["LW", "CAM"], 85],
    ],
  },
  2026: {
    Mexico: [
      ["Ochoa", "GK", 78],
      ["Rangel", "GK", 80],
      ["Acevedo", "GK", 77],
      ["Gallardo", "LB", 81],
      ["Montes", "CB", 82],
      ["Jorge Sánchez", "RB", 79],
      ["Vásquez", "CB", 83],
      ["Reyes", ["CB", "RB"], 80],
      ["Mateo Chávez", "LB", 77],
      ["E. Álvarez", "CDM", 83],
      ["Pineda", "CAM", 82],
      ["Alvarado", "RW", 80],
      ["Romo", "CM", 80],
      ["Luis Chávez", "CM", 79],
      ["Lira", "CDM", 77],
      ["Mora", "CAM", 80],
      ["B. Gutiérrez", "CM", 76],
      ["Vargas", "CDM", 77],
      ["Fidalgo", "CM", 78],
      ["R. Jiménez", "ST", 81],
      ["Vega", "LW", 81],
      ["S. Giménez", "ST", 79],
      ["Huerta", "LW", 78],
      ["Quiñones", "ST", 78],
      ["G. Martínez", "ST", 75],
      ["A. González", "ST", 76],
    ],
    "South Africa": [
      ["Williams", "GK", 83],
      ["Goss", "GK", 73],
      ["Chaine", "GK", 74],
      ["Modiba", "LB", 78],
      ["Mudau", "RB", 78],
      ["Sibisi", "CB", 76],
      ["Mbokazi", "CB", 74],
      ["Okon", "CB", 75],
      ["Kabini", "CB", 73],
      ["Ndamane", "CB", 74],
      ["Matuludi", "CB", 72],
      ["Sebelebele", "RB", 73],
      ["Cross", "LB", 72],
      ["Makhanya", "CB", 73],
      ["Mokoena", "CM", 80],
      ["Sithole", "CDM", 75],
      ["Mbatha", "CM", 74],
      ["Adams", "CM", 73],
      ["Zwane", "CAM", 78],
      ["Foster", "ST", 78],
      ["Makgopa", "ST", 75],
      ["Appollis", "LW", 77],
      ["Rayners", "ST", 75],
      ["Mofokeng", "RW", 76],
      ["Maseko", "RW", 74],
      ["Moremi", "RW", 73],
    ],
    "South Korea": [
      ["Kim Seung-gyu", "GK", 80],
      ["Jo Hyeon-woo", "GK", 79],
      ["Song Bum-keun", "GK", 75],
      ["Kim Min-jae", "CB", 85],
      ["Kim Moon-hwan", "RB", 76],
      ["Seol Young-woo", "RB", 77],
      ["Lee Tae-seok", "CB", 74],
      ["Park Jin-seob", "LB", 74],
      ["Kim Tae-hyeon", "CB", 74],
      ["Lee Han-beom", "CB", 75],
      ["Castrop", "CDM", 75],
      ["Lee Ki-hyuk", "CB", 73],
      ["Cho Wi-je", "CB", 73],
      ["Lee Jae-sung", "CM", 80],
      ["Hwang Hee-chan", "LW", 79],
      ["Hwang In-beom", "CDM", 80],
      ["Lee Kang-in", "CAM", 82],
      ["Paik Seung-ho", "CM", 76],
      ["Kim Jin-gyu", "CDM", 74],
      ["Lee Dong-gyeong", "CM", 75],
      ["Bae Jun-ho", "RW", 76],
      ["Eom Ji-sung", "LM", 74],
      ["Yang Hyun-jun", "RW", 74],
      ["Son Heung-min", ["LW", "ST"], 85],
      ["Cho Gue-sung", "ST", 77],
      ["Oh Hyeon-gyu", "ST", 76],
    ],
    Czechia: [
      ["Kovář", "GK", 78],
      ["Staněk", "GK", 79],
      ["Horníček", "GK", 74],
      ["Coufal", "RB", 79],
      ["Holeš", "CB", 78],
      ["L. Krejčí", "CB", 81],
      ["Zima", "CB", 76],
      ["Zelený", "LB", 75],
      ["Jurásek", "LB", 76],
      ["Douděra", "RB", 75],
      ["Hranáč", "CB", 76],
      ["Chaloupek", "CB", 73],
      ["Souček", "CM", 81],
      ["Darida", "CM", 75],
      ["Provod", "LW", 77],
      ["Sadílek", "CM", 75],
      ["Šulc", "CAM", 78],
      ["Červ", "CM", 74],
      ["Sochůrek", "CM", 72],
      ["Sojka", "CM", 72],
      ["Višinský", "CM", 72],
      ["Schick", "ST", 83],
      ["Hložek", "LW", 78],
      ["Kuchta", "ST", 75],
      ["Chytil", "ST", 74],
      ["Chorý", "ST", 74],
    ],
    Canada: [
      ["Crépeau", "GK", 79],
      ["St. Clair", "GK", 78],
      ["Goodman", "GK", 73],
      ["Davies", "LB", 83],
      ["Johnston", "RB", 81],
      ["Bombito", "CB", 78],
      ["Cornelius", "CB", 77],
      ["Laryea", ["RB", "LB"], 76],
      ["A. Jones", "CB", 75],
      ["Sigur", "RB", 75],
      ["De Fougerolles", "CB", 74],
      ["Waterman", "CB", 74],
      ["Eustáquio", "CM", 80],
      ["Koné", "CM", 78],
      ["Buchanan", "RW", 78],
      ["Osorio", "CM", 76],
      ["Millar", "LW", 76],
      ["Shaffelburg", "LW", 76],
      ["Choinière", "CM", 75],
      ["Flores", "CAM", 75],
      ["Ali Ahmed", "LM", 75],
      ["Saliba", "CM", 74],
      ["Jonathan David", "ST", 84],
      ["Larin", "ST", 79],
      ["Promise David", "ST", 77],
      ["Oluwaseyi", "ST", 76],
    ],
    Switzerland: [
      ["Kobel", "GK", 84],
      ["Keller", "GK", 74],
      ["Mvogo", "GK", 73],
      ["Akanji", "CB", 85],
      ["Elvedi", "CB", 80],
      ["Rodríguez", "LB", 79],
      ["Widmer", "RB", 78],
      ["Muheim", "LB", 75],
      ["Amenda", "CB", 75],
      ["Cömert", "CB", 74],
      ["Jaquez", "CB", 74],
      ["Xhaka", ["CM", "CDM"], 85],
      ["Zakaria", "CDM", 82],
      ["Jashari", "CM", 80],
      ["Freuler", "CM", 79],
      ["Sow", "CM", 77],
      ["Aebischer", ["CM", "LM"], 77],
      ["Rieder", "CAM", 77],
      ["Fassnacht", "RM", 76],
      ["Manzambi", "CM", 75],
      ["Ndoye", "RW", 83],
      ["Embolo", "ST", 82],
      ["Vargas", "LW", 79],
      ["Okafor", ["LW", "ST"], 78],
      ["Amdouni", "ST", 77],
      ["Itten", "ST", 74],
    ],
    Qatar: [
      ["Barsham", "GK", 77],
      ["Abunada", "GK", 73],
      ["Salah Zakaria", "GK", 72],
      ["Khoukhi", "CB", 77],
      ["Pedro Miguel", "RB", 75],
      ["Homam Al-Amin", "LB", 74],
      ["Lucas Mendes", "LB", 74],
      ["Sultan Al-Brake", ["RB", "LB"], 74],
      ["Al-Hashmi Al-Hussain", "CB", 73],
      ["Ayoub Al-Alawi", "CB", 73],
      ["Issa Laye", "CB", 73],
      ["Madibo", "CDM", 76],
      ["Boudiaf", "CDM", 75],
      ["Hatem", "CM", 75],
      ["A. Fathi", "CM", 74],
      ["Gaber", "CM", 73],
      ["Mannai", "CM", 73],
      ["Afif", ["RW", "CAM"], 81],
      ["Almoez Ali", "ST", 80],
      ["Al-Haydos", "CAM", 77],
      ["Edmílson Junior", "RW", 77],
      ["Muntari", "ST", 73],
      ["Abdurisag", "LW", 73],
      ["Alaaeldin", "RM", 73],
      ["Tahsin Mohammed", "CF", 73],
      ["Al-Ganehi", "RW", 72],
    ],
    "Bosnia and Herzegovina": [
      ["Vasilj", "GK", 78],
      ["Zlomislić", "GK", 73],
      ["O. Hadžikić", "GK", 72],
      ["Dedić", "RB", 80],
      ["Kolašinac", ["LB", "CB"], 78],
      ["Katić", "CB", 76],
      ["Muharemović", ["CB", "CDM"], 75],
      ["Mujakić", "CB", 74],
      ["Ćelik", ["RB", "LB"], 74],
      ["Radeljić", "CB", 73],
      ["Hadžikadunić", "CB", 73],
      ["Hadžiahmetović", "CDM", 76],
      ["Tahirović", "CM", 76],
      ["Gigović", "CM", 76],
      ["Šunjić", "CDM", 75],
      ["Alajbegović", "CAM", 75],
      ["Burnić", "CM", 73],
      ["Bašić", "CM", 72],
      ["Mahmić", "CM", 72],
      ["Bajraktarević", "LW", 77],
      ["Džeko", "ST", 80],
      ["Demirović", "ST", 79],
      ["Tabaković", "ST", 78],
      ["Memić", "ST", 73],
      ["Bazdar", "ST", 73],
      ["Lukić", "ST", 72],
    ],
    Argentina: [
      ["E. Martínez", "GK", 88],
      ["Molina", "RB", 80],
      ["C. Romero", "CB", 85],
      ["Otamendi", "CB", 80],
      ["Tagliafico", "LB", 80],
      ["Mac Allister", "CM", 86],
      ["E. Fernández", "CM", 84],
      ["De Paul", "CM", 83],
      ["Messi", "CF", 90],
      ["J. Álvarez", "ST", 87],
      ["L. Martínez", "ST", 86],
    ],
    France: [
      ["Maignan", "GK", 87],
      ["Koundé", "RB", 84],
      ["Saliba", "CB", 87],
      ["Upamecano", "CB", 84],
      ["T. Hernández", "LB", 83],
      ["Tchouaméni", "CDM", 86],
      ["Camavinga", "CM", 85],
      ["Griezmann", ["CAM", "LW"], 86],
      ["Dembélé", ["RW", "LW"], 88],
      ["Mbappé", ["LW", "ST"], 94],
      ["Kolo Muani", "ST", 82],
    ],
    Brazil: [
      ["Alisson", "GK", 88],
      ["Militão", "RB", 83],
      ["Marquinhos", "CB", 85],
      ["Gabriel", "CB", 85],
      ["Wendell", "LB", 80],
      ["B. Guimarães", "CDM", 86],
      ["Paquetá", "CAM", 83],
      ["Raphinha", "RW", 88],
      ["Vinícius", "LW", 89],
      ["Rodrygo", "RW", 85],
      ["Endrick", "ST", 81],
    ],
    England: [
      ["Pickford", "GK", 84],
      ["Alexander-Arnold", "RB", 87],
      ["Stones", "CB", 84],
      ["Guéhi", "CB", 83],
      ["Shaw", "LB", 81],
      ["Rice", "CDM", 88],
      ["Mainoo", "CM", 82],
      ["Bellingham", ["CAM", "CM"], 90],
      ["Saka", "RW", 88],
      ["Kane", "ST", 90],
      ["Foden", ["LW", "CAM"], 88],
    ],
    Portugal: [
      ["D. Costa", "GK", 83],
      ["Cancelo", "RB", 84],
      ["Rúben Dias", "CB", 87],
      ["Inácio", "CB", 81],
      ["N. Mendes", "LB", 84],
      ["Danilo", "CDM", 80],
      ["Vitinha", "CM", 88],
      ["B. Fernandes", "CAM", 86],
      ["R. Leão", "LW", 85],
      ["G. Ramos", "ST", 82],
      ["Pedro Neto", "RW", 83],
    ],
    Spain: [
      ["U. Simón", "GK", 84],
      ["Carvajal", "RB", 85],
      ["Le Normand", "CB", 82],
      ["Laporte", "CB", 83],
      ["Cucurella", "LB", 83],
      ["Rodri", "CDM", 91],
      ["Pedri", "CM", 88],
      ["Olmo", ["CAM", "LW"], 85],
      ["Yamal", "RW", 89],
      ["N. Williams", "LW", 85],
      ["Morata", "ST", 81],
    ],
    Germany: [
      ["ter Stegen", "GK", 87],
      ["Kimmich", ["RB", "CDM"], 87],
      ["Rüdiger", "CB", 85],
      ["Tah", "CB", 83],
      ["Raum", "LB", 80],
      ["Goretzka", "CDM", 83],
      ["Gündoğan", "CM", 83],
      ["Musiala", ["CAM", "LW"], 90],
      ["Wirtz", "LW", 90],
      ["Havertz", "ST", 84],
      ["Gnabry", "RW", 82],
    ],
    Netherlands: [
      ["Verbruggen", "GK", 82],
      ["Dumfries", "RB", 83],
      ["van Dijk", "CB", 86],
      ["de Ligt", "CB", 84],
      ["Aké", "LB", 82],
      ["F. de Jong", "CDM", 87],
      ["Reijnders", "CM", 84],
      ["Koopmeiners", "CAM", 84],
      ["Bergwijn", "RW", 81],
      ["Depay", "ST", 82],
      ["Gakpo", ["LW", "ST"], 86],
    ],
  },
};
