import type { DB } from "./types";

export const EDITIONS = [2010, 2014, 2018, 2022, 2026];

export const FLAGS: Record<string, string> = {
  Spain: "🇪🇸",
  Netherlands: "🇳🇱",
  Germany: "🇩🇪",
  Brazil: "🇧🇷",
  Argentina: "🇦🇷",
  Uruguay: "🇺🇾",
  Portugal: "🇵🇹",
  France: "🇫🇷",
  Belgium: "🇧🇪",
  Colombia: "🇨🇴",
  Croatia: "🇭🇷",
  England: "🇬🇧",
  Morocco: "🇲🇦",
};

export const WORLD_CUP_DB: DB = {
  2010: {
    Uruguay: [
      ["Fernando Muslera", "GK", 84],
      ["Diego Lugano", "CB", 87],
      ["Jorge Fucile", "RB", 81],
      ["Martín Cáceres", "CB", 84],
      ["Maxi Pereira", "RB", 82],
      ["Walter Gargano", "CDM", 80],
      ["Diego Pérez", "CDM", 79],
      ["Álvaro Pereira", "LM", 82],
      ["Egidio Arévalo Ríos", "CDM", 81],
      ["Nicolás Lodeiro", "CAM", 80],
      ["Rodrigo Palacio", "ST", 78],
      ["Sebastián Eguren", "CM", 78],
      ["Juan Castillo", "GK", 72],
      ["Mauricio Victorino", "CB", 78],
      ["Andrés Scotti", "CB", 79],
      ["Sebastián Coates", "CB", 76],
      ["Álvaro Fernández", "GK", 71],
      ["Alvaro González", "RM", 77],
      ["Néstor Muslera", "GK", 70],
      ["Diego Forlán", "ST", 91],
      ["Edinson Cavani", "ST", 88],
      ["Luis Suárez", "ST", 89],
      ["Abel Hernández", "ST", 77],
      ["Álvaro Pereira", "LM", 82],
    ],
    Mexico: [
      ["Óscar Pérez", "GK", 78],
      ["Joaquín Beltrán", "CB", 74],
      ["Francisco Rodríguez", "CB", 82],
      ["Rafael Márquez", "CB", 86],
      ["Carlos Salcido", "LB", 83],
      ["Gerardo Torrado", "CDM", 81],
      ["Andrés Guardado", "LM", 83],
      ["Efraín Juárez", "RB", 76],
      ["Giovani dos Santos", "RW", 83],
      ["Cuauhtémoc Blanco", "CAM", 79],
      ["Javier Hernández", "ST", 84],
      ["Alberto Medina", "RM", 74],
      ["Guillermo Ochoa", "GK", 80],
      ["Jonny Magallón", "CB", 77],
      ["Héctor Moreno", "CB", 81],
      ["Paul Aguilar", "RB", 75],
      ["Adolfo Bautista", "RM", 73],
      ["Israel Castro", "CDM", 76],
      ["Pablo Barrera", "RW", 79],
      ["Javier Aguirre", "CM", 70],
      ["Adrián Aldrete", "LB", 72],
      ["Gerardo Galindo", "CM", 71],
      ["Efrain Flores", "CM", 70],
      ["Francisco Palencia", "ST", 72],
    ],
    "South Africa": [
      ["Itumeleng Khune", "GK", 79],
      ["Siboniso Gaxa", "RB", 74],
      ["Bongani Khumalo", "CB", 76],
      ["Aaron Mokoena", "CB", 78],
      ["Lucas Thwala", "LB", 73],
      ["MacBeth Sibaya", "CDM", 74],
      ["Thanduyise Khuboni", "CM", 72],
      ["Siphiwe Tshabalala", "LM", 82],
      ["Steven Pienaar", "CAM", 81],
      ["Teko Modise", "CM", 77],
      ["Katlego Mphela", "ST", 80],
      ["Mandla Masango", "RW", 72],
      ["Moeneeb Josephs", "GK", 76],
      ["Lehlohonolo Majoro", "ST", 71],
      ["Nasief Morris", "CB", 72],
      ["Busa Mkhwanazi", "CB", 70],
      ["Anele Ngcongca", "RB", 73],
      ["Thulani Serero", "CAM", 73],
      ["Bernard Parker", "ST", 76],
      ["Kagisho Dikgacoi", "CDM", 75],
      ["Darren Keet", "GK", 70],
      ["Tsepo Masilela", "LB", 74],
      ["Siboniso Gaxa", "RB", 74],
      ["Mark Mayambela", "LW", 72],
    ],
    France: [
      ["Hugo Lloris", "GK", 83],
      ["Steve Mandanda", "GK", 80],
      ["Cédric Carrasso", "GK", 76],
      ["Patrice Evra", "LB", 82],
      ["William Gallas", "CB", 81],
      ["Abou Diaby", "CM", 78],
      ["Yohan Gourcuff", "CAM", 79],
      ["Alou Diarra", "CDM", 77],
      ["Éric Abidal", "LB", 80],
      ["Bakary Sagna", "RB", 79],
      ["Thierry Henry", "ST", 78],
      ["Franck Ribéry", "LW", 84],
      ["Nicolas Anelka", "ST", 77],
      ["Jérémy Toulalan", "CDM", 78],
      ["Florent Malouda", "LM", 80],
      ["Nicolas Plestan", "CB", 71],
      ["Gaël Clichy", "LB", 75],
      ["Mathieu Valbuena", "RW", 80],
      ["Abou Diaby", "CM", 78],
      ["Sidney Govou", "RW", 74],
      ["André-Pierre Gignac", "ST", 75],
      ["Yoann Gourcuff", "CAM", 79],
      ["Jean-Alain Boumsong", "CB", 72],
      ["William Gallas", "CB", 81],
    ],
    Argentina: [
      ["Sergio Romero", "GK", 84],
      ["Diego Pozo", "GK", 72],
      ["Nicolás Otamendi", "CB", 78],
      ["Martín Demichelis", "CB", 81],
      ["Walter Samuel", "CB", 82],
      ["Gabriel Heinze", "LB", 79],
      ["Jonás Gutiérrez", "RM", 77],
      ["Marcos Angeleri", "RB", 72],
      ["Nicolás Burdisso", "CB", 76],
      ["Javier Zanetti", "RB", 80],
      ["Javier Mascherano", "CDM", 88],
      ["Juan Sebastián Verón", "CM", 78],
      ["Ángel Di María", "LW", 84],
      ["Fernando Gago", "CM", 76],
      ["Maxi Rodríguez", "LM", 78],
      ["Mario Bolatti", "CM", 73],
      ["Juan Sebastián Verón", "CM", 78],
      ["Javier Pastore", "CAM", 77],
      ["Éver Banega", "CM", 76],
      ["Lionel Messi", "CF", 92],
      ["Carlos Tévez", "ST", 87],
      ["Gonzalo Higuaín", "ST", 90],
      ["Diego Milito", "ST", 85],
    ],
    Nigeria: [
      ["Vincent Enyeama", "GK", 84],
      ["Austin Ejide", "GK", 74],
      ["Peter Odemwingie", "RW", 82],
      ["Chidi Odiah", "RB", 74],
      ["Joseph Yobo", "CB", 80],
      ["Taye Taiwo", "LB", 81],
      ["Danny Shittu", "CB", 73],
      ["Rabiu Afolabi", "CB", 72],
      ["Dickson Etuhu", "CDM", 76],
      ["Ayila Yussuf", "CDM", 74],
      ["Kalu Uche", "CM", 75],
      ["Ogenyi Onazi", "CM", 70],
      ["John Mikel Obi", "CM", 83],
      ["Sani Kaita", "CDM", 72],
      ["Elderson Echiejile", "LB", 71],
      ["Victor Anichebe", "ST", 74],
      ["Yakubu Aiyegbeni", "ST", 78],
      ["Chinedu Obasi", "RW", 77],
      ["Kanu", "CF", 75],
      ["Obafemi Martins", "ST", 79],
      ["Daniel Shittu", "CB", 73],
      ["Aiyegbeni Yakubu", "ST", 78],
      ["Victor Nsofor", "LW", 76],
    ],
    "South Korea": [
      ["Jung Sung-ryong", "GK", 80],
      ["Lee Woon-jae", "GK", 73],
      ["Lee Young-pyo", "LB", 82],
      ["Cha Du-ri", "RB", 78],
      ["Kim Jae-sung", "CB", 74],
      ["Cho Sung-hwan", "CB", 75],
      ["Lee Jung-soo", "CB", 79],
      ["Kim Nam-il", "CDM", 77],
      ["Park Ji-sung", "CM", 86],
      ["Ki Sung-yueng", "CM", 80],
      ["Kim Jung-woo", "CM", 76],
      ["Lee Chung-yong", "RW", 83],
      ["Park Chu-young", "ST", 81],
      ["Yeom Ki-hun", "LM", 76],
      ["Moon Tae-jong", "CM", 71],
      ["Lee Dong-gook", "ST", 74],
      ["Hwang Jae-won", "RB", 73],
      ["Kim Dong-jin", "LB", 74],
      ["Lee Ho", "CDM", 72],
      ["Oh Beom-seok", "RB", 71],
      ["Song Chong-gug", "RB", 70],
      ["Kim Bo-kyung", "CAM", 74],
      ["Yeom Ki-hun", "LM", 76],
    ],
    Greece: [
      ["Alexandros Tzorvas", "GK", 79],
      ["Michalis Sifakis", "GK", 74],
      ["Vasilis Torosidis", "RB", 81],
      ["Sokratis Papastathopoulos", "CB", 82],
      ["Loukas Vintra", "CB", 76],
      ["Avraam Papadopoulos", "CB", 78],
      ["Giourkas Seitaridis", "RB", 74],
      ["Vasilis Karagounis", "CM", 80],
      ["Kostas Katsouranis", "CDM", 82],
      ["Giorgos Karagounis", "CAM", 83],
      ["Giorgos Samaras", "LW", 81],
      ["Dimitris Salpingidis", "ST", 82],
      ["Theofanis Gekas", "ST", 84],
      ["Sotiris Ninis", "CAM", 77],
      ["Vangelis Moras", "CB", 75],
      ["Christos Patsatzoglou", "CDM", 74],
      ["Alexandros Tziolis", "CM", 73],
      ["Kostas Chalkias", "GK", 71],
      ["Dimitrios Papadopoulos", "ST", 75],
      ["Giorgos Fotakis", "CM", 74],
      ["Nikos Spiropoulos", "LB", 75],
      ["Jose Holebas", "LB", 73],
      ["Lazaros Christodoulopoulos", "RW", 74],
    ],
    England: [
      ["David James", "GK", 78],
      ["Robert Green", "GK", 72],
      ["Joe Hart", "GK", 74],
      ["Glen Johnson", "RB", 80],
      ["Jamie Carragher", "CB", 73],
      ["John Terry", "CB", 79],
      ["Ledley King", "CB", 76],
      ["Rio Ferdinand", "CB", 70],
      ["Matthew Upson", "CB", 77],
      ["Ashley Cole", "LB", 84],
      ["Stephen Warnock", "LB", 71],
      ["Michael Dawson", "CB", 72],
      ["Steven Gerrard", "CM", 84],
      ["Frank Lampard", "CM", 82],
      ["Gareth Barry", "CDM", 76],
      ["James Milner", "RM", 79],
      ["Aaron Lennon", "RW", 74],
      ["Joe Cole", "LW", 72],
      ["Shaun Wright-Phillips", "RW", 71],
      ["Tom Huddlestone", "CM", 70],
      ["Peter Crouch", "ST", 75],
      ["Wayne Rooney", "ST", 74],
      ["Jermain Defoe", "ST", 76],
    ],
    USA: [
      ["Tim Howard", "GK", 86],
      ["Brad Guzan", "GK", 72],
      ["Marcus Hahnemann", "GK", 71],
      ["Carlos Bocanegra", "LB", 80],
      ["Jay DeMerit", "CB", 78],
      ["Oguchi Onyewu", "CB", 72],
      ["Jonathan Bornstein", "LB", 70],
      ["Steve Cherundolo", "RB", 84],
      ["Jonathan Spector", "RB", 71],
      ["Clarence Goodson", "CB", 73],
      ["Chad Marshall", "CB", 70],
      ["Michael Bradley", "CM", 83],
      ["Clint Dempsey", "RW", 87],
      ["Landon Donovan", "RW", 90],
      ["Ricardo Clark", "CDM", 71],
      ["Maurice Edu", "CDM", 75],
      ["Benny Feilhaber", "CM", 76],
      ["José Francisco Torres", "CM", 72],
      ["Stuart Holden", "RM", 73],
      ["DaMarcus Beasley", "LM", 71],
      ["Jozy Altidore", "ST", 78],
      ["Edson Buddle", "ST", 72],
      ["Herculez Gomez", "ST", 73],
    ],
    Algeria: [
      ["Faouzi Chaouchi", "GK", 74],
      ["Rais M'Bolhi", "GK", 81],
      ["Mohamed Lamine Zemmamouche", "GK", 70],
      ["Madjid Bougherra", "CB", 82],
      ["Rafik Halliche", "CB", 78],
      ["Abdelkader Laïfaoui", "CB", 71],
      ["Carl Medjani", "CB", 74],
      ["Nadir Belhadj", "LB", 80],
      ["Mehdi Lacen", "CDM", 79],
      ["Adlane Guedioura", "CDM", 75],
      ["Hassan Yebda", "CM", 78],
      ["Karim Ziani", "RM", 80],
      ["Mourad Meghni", "CAM", 70],
      ["Yazid Mansouri", "CDM", 73],
      ["Foued Kadir", "RM", 72],
      ["Ryad Boudebouz", "CAM", 70],
      ["Djamel Abdoun", "RW", 71],
      ["Khaled Lemmouchia", "CM", 70],
      ["Abdelmalek Ziaya", "ST", 71],
      ["Rafik Saïfi", "CF", 70],
      ["Nadir Bouazza", "LW", 70],
      ["Rafik Djebbour", "ST", 74],
      ["Kamel Ghilas", "ST", 72],
    ],
    Slovenia: [
      ["Samir Handanović", "GK", 84],
      ["Jasmin Handanović", "GK", 70],
      ["Aleksander Seliga", "GK", 71],
      ["Boštjan Cesar", "CB", 81],
      ["Marko Šuler", "CB", 77],
      ["Miran Pavlin", "CB", 70],
      ["Suad Fileković", "CB", 70],
      ["Mišo Brečko", "RB", 78],
      ["Bojan Jokić", "LB", 79],
      ["Branko Ilič", "RB", 74],
      ["Valter Birsa", "RW", 81],
      ["Andraž Kirm", "LM", 79],
      ["Robert Koren", "CM", 83],
      ["Aleksandar Radosavljevič", "CDM", 76],
      ["Dalibor Stevanovič", "CM", 74],
      ["Rene Krhin", "CDM", 72],
      ["Matej Mavrič", "CB", 70],
      ["Nejc Pečnik", "RM", 71],
      ["Zlatko Dedič", "ST", 78],
      ["Milivoje Novakovič", "ST", 82],
      ["Tim Matavž", "ST", 72],
      ["Zlatan Ljubijankić", "ST", 75],
      ["Etien Velikonja", "ST", 70],
    ],
    Spain: [
      ["Casillas", "GK", 92],
      ["S. Ramos", "RB", 86],
      ["Piqué", "CB", 85],
      ["Puyol", "CB", 86],
      ["Capdevila", "LB", 79],
      ["Xavi", "CM", 93],
      ["Iniesta", "CM", 92],
      ["Busquets", "CDM", 84],
      ["X. Alonso", "CDM", 86],
      ["D. Villa", "ST", 89],
      ["F. Torres", "CF", 82],
      ["Pedro", "RW", 80],
    ],
    Netherlands: [
      ["Stekelenburg", "GK", 80],
      ["van der Wiel", "RB", 78],
      ["Heitinga", "CB", 79],
      ["Mathijsen", "CB", 78],
      ["van Bronckhorst", "LB", 80],
      ["van Bommel", "CDM", 82],
      ["de Jong", "CDM", 81],
      ["Sneijder", "CAM", 90],
      ["Kuyt", "RM", 81],
      ["Robben", "RW", 90],
      ["van Persie", "ST", 84],
    ],
    Germany: [
      ["Neuer", "GK", 84],
      ["Lahm", "RB", 86],
      ["Mertesacker", "CB", 79],
      ["Friedrich", "CB", 77],
      ["Boateng", "LB", 78],
      ["Schweinsteiger", "CM", 87],
      ["Khedira", "CDM", 80],
      ["Özil", "CAM", 85],
      ["Müller", ["RW", "CAM"], 86],
      ["Klose", "ST", 85],
      ["Podolski", "LW", 81],
    ],
    Brazil: [
      ["Júlio César", "GK", 85],
      ["Maicon", "RB", 85],
      ["Lúcio", "CB", 83],
      ["Juan", "CB", 80],
      ["Bastos", "LB", 76],
      ["G. Silva", "CDM", 80],
      ["Felipe Melo", "CM", 78],
      ["Kaká", "CAM", 87],
      ["Elano", "RM", 79],
      ["Robinho", "LW", 83],
      ["Luís Fabiano", "ST", 81],
    ],
    Portugal: [
      ["Eduardo", "GK", 76],
      ["Bruno Alves", "CB", 79],
      ["R. Carvalho", "CB", 84],
      ["Coentrão", "LB", 79],
      ["Miguel", "RB", 75],
      ["Tiago", "CM", 78],
      ["Meireles", "CDM", 80],
      ["Deco", "CAM", 82],
      ["Simão", "RM", 79],
      ["Ronaldo", "LW", 90],
      ["Almeida", "ST", 76],
    ],
  },
  2014: {
    Germany: [
      ["Neuer", "GK", 90],
      ["Lahm", "RB", 88],
      ["Boateng", "CB", 84],
      ["Hummels", "CB", 85],
      ["Höwedes", "LB", 80],
      ["Schweinsteiger", "CDM", 87],
      ["Kroos", "CM", 88],
      ["Müller", ["RW", "CAM"], 89],
      ["Özil", "CAM", 86],
      ["Götze", "CF", 82],
      ["Klose", "ST", 83],
    ],
    Argentina: [
      ["Romero", "GK", 82],
      ["Zabaleta", "RB", 82],
      ["Garay", "CB", 82],
      ["Demichelis", "CB", 79],
      ["Rojo", "LB", 79],
      ["Mascherano", "CDM", 88],
      ["Biglia", "CM", 79],
      ["Di María", ["LW", "RM"], 87],
      ["Messi", ["RW", "CF"], 94],
      ["Higuaín", "ST", 84],
      ["Lavezzi", "CF", 80],
    ],
    Netherlands: [
      ["Cillessen", "GK", 79],
      ["Vlaar", "CB", 80],
      ["de Vrij", "CB", 80],
      ["M. Indi", "CB", 78],
      ["Blind", "LB", 80],
      ["de Jong", "CDM", 82],
      ["Wijnaldum", "CM", 80],
      ["Sneijder", "CAM", 86],
      ["Robben", "RW", 91],
      ["van Persie", "ST", 87],
      ["Kuyt", "LM", 78],
    ],
    Brazil: [
      ["Júlio César", "GK", 82],
      ["Dani Alves", "RB", 84],
      ["Thiago Silva", "CB", 88],
      ["David Luiz", "CB", 83],
      ["Marcelo", "LB", 85],
      ["Paulinho", "CDM", 80],
      ["Fernandinho", "CM", 80],
      ["Oscar", "CAM", 83],
      ["Hulk", "LW", 82],
      ["Neymar", "CF", 88],
      ["Fred", "ST", 78],
    ],
    France: [
      ["Lloris", "GK", 85],
      ["Sagna", "RB", 80],
      ["Varane", "CB", 83],
      ["Sakho", "CB", 80],
      ["Evra", "LB", 80],
      ["Matuidi", "CM", 82],
      ["Pogba", "CM", 84],
      ["Valbuena", "CAM", 80],
      ["Benzema", "CF", 87],
      ["Giroud", "ST", 81],
      ["Griezmann", ["LW", "CAM"], 79],
    ],
    Belgium: [
      ["Courtois", "GK", 85],
      ["Alderweireld", "CB", 83],
      ["Kompany", "CB", 86],
      ["Vertonghen", "CB", 84],
      ["Meunier", "RB", 78],
      ["Witsel", "CDM", 82],
      ["Fellaini", "CM", 80],
      ["De Bruyne", ["CAM", "CM"], 84],
      ["Hazard", ["LW", "CAM"], 88],
      ["Lukaku", "ST", 82],
      ["Mertens", "CF", 80],
    ],
    Colombia: [
      ["Ospina", "GK", 80],
      ["Zúñiga", "RB", 78],
      ["Yepes", "CB", 79],
      ["Zapata", "CB", 77],
      ["Armero", "LB", 77],
      ["Aguilar", "CDM", 77],
      ["C. Sánchez", "CM", 78],
      ["James", "CAM", 87],
      ["Cuadrado", "RW", 83],
      ["T. Gutiérrez", "LW", 78],
      ["J. Martínez", "ST", 78],
    ],
  },
  2018: {
    France: [
      ["Lloris", "GK", 87],
      ["Pavard", "RB", 81],
      ["Varane", "CB", 87],
      ["Umtiti", "CB", 83],
      ["L. Hernández", "LB", 81],
      ["Kanté", "CDM", 88],
      ["Pogba", "CM", 87],
      ["Griezmann", ["CAM", "LW"], 90],
      ["Dembélé", ["RW", "LW"], 82],
      ["Mbappé", ["LW", "ST"], 89],
      ["Giroud", "ST", 82],
    ],
    Croatia: [
      ["Subašić", "GK", 82],
      ["Vrsaljko", "RB", 81],
      ["Lovren", "CB", 82],
      ["Vida", "CB", 79],
      ["Strinić", "LB", 78],
      ["Brozović", "CDM", 82],
      ["Modrić", ["CM", "CAM"], 92],
      ["Rakitić", "CM", 86],
      ["Rebić", "LW", 79],
      ["Mandžukić", "ST", 84],
      ["Perišić", "LW", 84],
    ],
    Belgium: [
      ["Courtois", "GK", 88],
      ["Alderweireld", "CB", 85],
      ["Kompany", "CB", 84],
      ["Vertonghen", "CB", 84],
      ["Meunier", "RB", 80],
      ["Witsel", "CDM", 83],
      ["De Bruyne", ["CAM", "CM"], 91],
      ["Hazard", ["LW", "CAM"], 91],
      ["Mertens", "CF", 82],
      ["Lukaku", "ST", 86],
      ["T. Hazard", "LM", 79],
    ],
    England: [
      ["Pickford", "GK", 81],
      ["Walker", "RB", 83],
      ["Stones", "CB", 81],
      ["Maguire", "CB", 81],
      ["Trippier", "LB", 81],
      ["Henderson", "CDM", 81],
      ["Lingard", "CM", 80],
      ["Alli", "CAM", 82],
      ["Sterling", "LW", 84],
      ["Kane", "ST", 88],
      ["Rashford", "RW", 81],
    ],
    Brazil: [
      ["Alisson", "GK", 87],
      ["Fagner", "RB", 80],
      ["Thiago Silva", "CB", 85],
      ["Miranda", "CB", 82],
      ["Filipe Luís", "LB", 84],
      ["Casemiro", "CDM", 86],
      ["Paulinho", "CM", 80],
      ["Coutinho", "LW", 86],
      ["Willian", "RW", 82],
      ["Neymar", ["CF", "LW"], 90],
      ["Firmino", "ST", 82],
    ],
    Uruguay: [
      ["Muslera", "GK", 82],
      ["Cáceres", "RB", 79],
      ["Godín", "CB", 88],
      ["Giménez", "CB", 84],
      ["Laxalt", "LB", 78],
      ["Torreira", "CDM", 79],
      ["Bentancur", "CM", 79],
      ["Nández", "CM", 78],
      ["De Arrascaeta", "LW", 80],
      ["Suárez", "CF", 88],
      ["Cavani", "ST", 86],
    ],
    Portugal: [
      ["Rui Patrício", "GK", 83],
      ["Ricardo Pereira", "RB", 80],
      ["Pepe", "CB", 84],
      ["Rúben Dias", "CB", 79],
      ["Guerreiro", "LB", 80],
      ["William Carvalho", "CDM", 78],
      ["Moutinho", "CM", 80],
      ["B. Fernandes", "CAM", 85],
      ["Quaresma", "RM", 79],
      ["Ronaldo", "LW", 93],
      ["A. Silva", "ST", 78],
    ],
  },
  2022: {
    Argentina: [
      ["E. Martínez", "GK", 87],
      ["Molina", "RB", 80],
      ["C. Romero", "CB", 84],
      ["Otamendi", "CB", 82],
      ["Tagliafico", "LB", 80],
      ["De Paul", "CM", 84],
      ["E. Fernández", "CM", 84],
      ["Mac Allister", "CM", 84],
      ["Di María", ["LW", "RW"], 86],
      ["Messi", "CF", 95],
      ["J. Álvarez", "ST", 84],
    ],
    France: [
      ["Lloris", "GK", 85],
      ["Pavard", "RB", 83],
      ["Varane", "CB", 85],
      ["Upamecano", "CB", 82],
      ["T. Hernández", "LB", 84],
      ["Tchouaméni", "CDM", 84],
      ["Camavinga", "CM", 82],
      ["Griezmann", ["CAM", "LW"], 88],
      ["Dembélé", ["RW", "LW"], 83],
      ["Mbappé", ["LW", "ST"], 93],
      ["Giroud", "ST", 82],
    ],
    Croatia: [
      ["Livaković", "GK", 83],
      ["Juranović", "RB", 80],
      ["Lovren", "CB", 80],
      ["Gvardiol", "LB", 84],
      ["Sosa", "LWB", 79],
      ["Brozović", "CDM", 84],
      ["Modrić", ["CAM", "CM"], 88],
      ["Kovačić", "CM", 83],
      ["Vlašić", "RM", 79],
      ["Kramarić", "CF", 81],
      ["Perišić", "LW", 84],
    ],
    Morocco: [
      ["Bono", "GK", 85],
      ["Hakimi", "RB", 85],
      ["Saïss", "CB", 80],
      ["Aguerd", "CB", 80],
      ["Mazraoui", "LB", 81],
      ["Amrabat", "CDM", 85],
      ["Ounahi", "CM", 80],
      ["Amallah", "CM", 78],
      ["Ziyech", "RW", 83],
      ["Boufal", "LW", 80],
      ["En-Nesyri", "ST", 81],
    ],
    Brazil: [
      ["Alisson", "GK", 89],
      ["Militão", "RB", 83],
      ["Marquinhos", "CB", 86],
      ["Thiago Silva", "CB", 84],
      ["Alex Sandro", "LB", 81],
      ["Casemiro", "CDM", 87],
      ["Paquetá", "CAM", 82],
      ["Raphinha", "RW", 82],
      ["Neymar", ["CF", "LW"], 89],
      ["Vinícius", "LW", 86],
      ["Richarlison", "ST", 82],
    ],
    Portugal: [
      ["D. Costa", "GK", 80],
      ["Cancelo", "RB", 86],
      ["Pepe", "CB", 82],
      ["Rúben Dias", "CB", 87],
      ["Guerreiro", "LB", 82],
      ["Danilo", "CDM", 80],
      ["Vitinha", "CM", 82],
      ["B. Fernandes", "CAM", 86],
      ["R. Leão", "LW", 83],
      ["Ronaldo", "CF", 87],
      ["G. Ramos", "ST", 80],
    ],
    Netherlands: [
      ["Noppert", "GK", 79],
      ["Dumfries", "RB", 82],
      ["van Dijk", "CB", 89],
      ["de Ligt", "CB", 83],
      ["Blind", "LB", 80],
      ["F. de Jong", "CDM", 87],
      ["Koopmeiners", "CM", 82],
      ["Berghuis", "CAM", 80],
      ["Bergwijn", "RW", 80],
      ["Depay", "ST", 84],
      ["Gakpo", ["LW", "ST"], 84],
    ],
    England: [
      ["Pickford", "GK", 83],
      ["Walker", "RB", 83],
      ["Stones", "CB", 84],
      ["Maguire", "CB", 80],
      ["Shaw", "LB", 82],
      ["Rice", "CDM", 84],
      ["Bellingham", ["CM", "CAM"], 86],
      ["Mount", "CAM", 82],
      ["Saka", "RW", 85],
      ["Kane", "ST", 89],
      ["Foden", ["LW", "CAM"], 85],
    ],
  },
  2026: {
    Argentina: [
      ["E. Martínez", "GK", 88],
      ["Molina", "RB", 80],
      ["C. Romero", "CB", 85],
      ["Otamendi", "CB", 80],
      ["Tagliafico", "LB", 80],
      ["Mac Allister", "CM", 86],
      ["E. Fernández", "CM", 84],
      ["De Paul", "CM", 83],
      ["Messi", "CF", 90],
      ["J. Álvarez", "ST", 87],
      ["L. Martínez", "ST", 86],
    ],
    France: [
      ["Maignan", "GK", 87],
      ["Koundé", "RB", 84],
      ["Saliba", "CB", 87],
      ["Upamecano", "CB", 84],
      ["T. Hernández", "LB", 83],
      ["Tchouaméni", "CDM", 86],
      ["Camavinga", "CM", 85],
      ["Griezmann", ["CAM", "LW"], 86],
      ["Dembélé", ["RW", "LW"], 88],
      ["Mbappé", ["LW", "ST"], 94],
      ["Kolo Muani", "ST", 82],
    ],
    Brazil: [
      ["Alisson", "GK", 88],
      ["Militão", "RB", 83],
      ["Marquinhos", "CB", 85],
      ["Gabriel", "CB", 85],
      ["Wendell", "LB", 80],
      ["B. Guimarães", "CDM", 86],
      ["Paquetá", "CAM", 83],
      ["Raphinha", "RW", 88],
      ["Vinícius", "LW", 89],
      ["Rodrygo", "RW", 85],
      ["Endrick", "ST", 81],
    ],
    England: [
      ["Pickford", "GK", 84],
      ["Alexander-Arnold", "RB", 87],
      ["Stones", "CB", 84],
      ["Guéhi", "CB", 83],
      ["Shaw", "LB", 81],
      ["Rice", "CDM", 88],
      ["Mainoo", "CM", 82],
      ["Bellingham", ["CAM", "CM"], 90],
      ["Saka", "RW", 88],
      ["Kane", "ST", 90],
      ["Foden", ["LW", "CAM"], 88],
    ],
    Portugal: [
      ["D. Costa", "GK", 83],
      ["Cancelo", "RB", 84],
      ["Rúben Dias", "CB", 87],
      ["Inácio", "CB", 81],
      ["N. Mendes", "LB", 84],
      ["Danilo", "CDM", 80],
      ["Vitinha", "CM", 88],
      ["B. Fernandes", "CAM", 86],
      ["R. Leão", "LW", 85],
      ["G. Ramos", "ST", 82],
      ["Pedro Neto", "RW", 83],
    ],
    Spain: [
      ["U. Simón", "GK", 84],
      ["Carvajal", "RB", 85],
      ["Le Normand", "CB", 82],
      ["Laporte", "CB", 83],
      ["Cucurella", "LB", 83],
      ["Rodri", "CDM", 91],
      ["Pedri", "CM", 88],
      ["Olmo", ["CAM", "LW"], 85],
      ["Yamal", "RW", 89],
      ["N. Williams", "LW", 85],
      ["Morata", "ST", 81],
    ],
    Germany: [
      ["ter Stegen", "GK", 87],
      ["Kimmich", ["RB", "CDM"], 87],
      ["Rüdiger", "CB", 85],
      ["Tah", "CB", 83],
      ["Raum", "LB", 80],
      ["Goretzka", "CDM", 83],
      ["Gündoğan", "CM", 83],
      ["Musiala", ["CAM", "LW"], 90],
      ["Wirtz", "LW", 90],
      ["Havertz", "ST", 84],
      ["Gnabry", "RW", 82],
    ],
    Netherlands: [
      ["Verbruggen", "GK", 82],
      ["Dumfries", "RB", 83],
      ["van Dijk", "CB", 86],
      ["de Ligt", "CB", 84],
      ["Aké", "LB", 82],
      ["F. de Jong", "CDM", 87],
      ["Reijnders", "CM", 84],
      ["Koopmeiners", "CAM", 84],
      ["Bergwijn", "RW", 81],
      ["Depay", "ST", 82],
      ["Gakpo", ["LW", "ST"], 86],
    ],
  },
};
